// 题库：{c:分类, t:主题, q:题目, o:选项, a:正确答案下标, e:解析}
const QUESTIONS = [
// ===== Java =====
{c:'java',t:'基础',q:'Java 中 int 类型占用多少位？',o:['16 位','32 位','64 位','取决于平台'],a:1,e:'Java 的 int 固定为 32 位有符号整数，与平台无关。'},
{c:'java',t:'基础',q:'以下哪个不是 Java 的基本数据类型？',o:['byte','char','String','boolean'],a:2,e:'String 是引用类型（类），8 种基本类型不包含它。'},
{c:'java',t:'基础',q:'表达式 10 / 4 在 Java 中的结果是？',o:['2.5','2','3','2.0'],a:1,e:'两个 int 相除为整数除法，结果截断为 2。'},
{c:'java',t:'基础',q:'对于两个 String 对象，== 比较的是什么？',o:['字符串内容','引用地址','哈希值','长度'],a:1,e:'== 比较引用是否指向同一对象；比较内容应使用 equals()。'},
{c:'java',t:'基础',q:'关于 String 的说法，正确的是？',o:['String 是可变的','String 被 final 修饰且不可变','String 是基本类型','String 不能被用作 HashMap 的键'],a:1,e:'String 类是 final 的，其对象创建后内容不可修改。'},
{c:'java',t:'基础',q:'在单线程中频繁拼接字符串，最推荐使用？',o:['String','StringBuffer','StringBuilder','char[]'],a:2,e:'StringBuilder 可变且无同步开销；StringBuffer 是线程安全版本，较慢。'},
{c:'java',t:'基础',q:'Java 方法参数的传递方式是？',o:['总是按引用传递','总是按值传递','基本类型按值，对象按引用','由编译器决定'],a:1,e:'Java 只有值传递；对象参数传递的是引用的副本。'},
{c:'java',t:'基础',q:'Integer a = 127, b = 127; a == b 的结果是？',o:['true','false','编译错误','运行时异常'],a:0,e:'Integer 缓存了 -128~127 的对象，自动装箱返回同一实例。'},
{c:'java',t:'OOP',q:'Java 中一个类可以直接继承几个父类？',o:['0 个','1 个','2 个','任意多个'],a:1,e:'Java 类只支持单继承，但可以实现多个接口。'},
{c:'java',t:'OOP',q:'方法重载（Overload）的判定依据是？',o:['返回值类型不同','参数列表不同','访问修饰符不同','抛出异常不同'],a:1,e:'重载要求同名方法参数列表（个数、类型或顺序）不同，仅返回值不同不构成重载。'},
{c:'java',t:'OOP',q:'被 final 修饰的类有什么特点？',o:['不能被实例化','不能被继承','所有方法都是静态的','不能有构造器'],a:1,e:'final 类不能被继承，如 String；但可以正常实例化。'},
{c:'java',t:'OOP',q:'关于抽象类，正确的是？',o:['可以直接 new 实例','必须包含抽象方法','可以有构造方法','不能有普通方法'],a:2,e:'抽象类可以有构造方法（供子类调用），但不能直接实例化，也不强制含抽象方法。'},
{c:'java',t:'OOP',q:'protected 成员可以被谁访问？',o:['仅本类','本类和同包类','同包类及其他包中的子类','所有类'],a:2,e:'protected 允许同包访问，以及不同包中的子类访问。'},
{c:'java',t:'OOP',q:'Java 8 起，接口中可以包含以下哪种带方法体的方法？',o:['default 方法','protected 方法','final 方法','synchronized 方法'],a:0,e:'Java 8 引入 default 方法和 static 方法，接口可提供默认实现。'},
{c:'java',t:'OOP',q:'重写 equals() 时通常还必须重写哪个方法？',o:['toString()','hashCode()','clone()','finalize()'],a:1,e:'相等的对象必须有相同的 hashCode，否则在 HashMap/HashSet 中会出错。'},
{c:'java',t:'集合',q:'HashMap 是否允许 null 键？',o:['不允许','允许一个 null 键','允许多个 null 键','仅 Java 8 以前允许'],a:1,e:'HashMap 允许一个 null 键和多个 null 值；Hashtable 两者都不允许。'},
{c:'java',t:'集合',q:'以下哪个集合不允许重复元素？',o:['ArrayList','LinkedList','HashSet','Vector'],a:2,e:'Set 接口的实现（如 HashSet）不允许重复元素。'},
{c:'java',t:'集合',q:'ArrayList 按下标随机访问 get(i) 的时间复杂度是？',o:['O(1)','O(log n)','O(n)','O(n log n)'],a:0,e:'ArrayList 底层是数组，按下标访问为 O(1)。'},
{c:'java',t:'集合',q:'需要按键自然顺序排序的 Map，应选择？',o:['HashMap','LinkedHashMap','TreeMap','Hashtable'],a:2,e:'TreeMap 基于红黑树，按键的自然顺序或 Comparator 排序。'},
{c:'java',t:'集合',q:'用增强 for 遍历 ArrayList 时直接调用 list.remove(obj)，通常会抛出？',o:['NullPointerException','ConcurrentModificationException','IndexOutOfBoundsException','ClassCastException'],a:1,e:'迭代期间结构被修改触发 fail-fast 机制；应使用 Iterator.remove() 或 removeIf()。'},
{c:'java',t:'集合',q:'多线程环境下推荐使用的高并发 Map 是？',o:['HashMap','TreeMap','ConcurrentHashMap','LinkedHashMap'],a:2,e:'ConcurrentHashMap 采用细粒度锁/CAS，比 Hashtable 并发性能更好。'},
{c:'java',t:'异常',q:'以下哪个是受检异常（checked exception）？',o:['NullPointerException','ArithmeticException','IOException','IllegalArgumentException'],a:2,e:'IOException 继承自 Exception 而非 RuntimeException，必须捕获或声明。'},
{c:'java',t:'异常',q:'try 块中执行了 return，finally 块会执行吗？',o:['不会执行','会在 return 返回前执行','只有发生异常时执行','编译错误'],a:1,e:'finally 在方法返回前执行，除非 JVM 退出（如 System.exit）。'},
{c:'java',t:'异常',q:'Error 和 Exception 的共同父类是？',o:['Object','RuntimeException','Throwable','Serializable'],a:2,e:'Throwable 是所有错误和异常的父类。'},
{c:'java',t:'异常',q:'try-with-resources 要求资源实现哪个接口？',o:['Closeable 或 AutoCloseable','Serializable','Runnable','Iterable'],a:0,e:'资源需实现 AutoCloseable（Closeable 是其子接口），块结束时自动关闭。'},
{c:'java',t:'多线程',q:'启动一个新线程应调用 Thread 的哪个方法？',o:['run()','start()','execute()','init()'],a:1,e:'start() 创建新线程并调用 run()；直接调用 run() 只是普通方法调用。'},
{c:'java',t:'多线程',q:'volatile 关键字能保证什么？',o:['原子性','可见性和禁止指令重排序','互斥访问','线程安全的 i++'],a:1,e:'volatile 保证可见性与有序性，但不保证复合操作（如 i++）的原子性。'},
{c:'java',t:'多线程',q:'sleep() 与 wait() 的区别，正确的是？',o:['sleep() 会释放锁','wait() 会释放对象锁','两者都必须在 synchronized 中调用','wait() 是 Thread 类的方法'],a:1,e:'wait() 是 Object 方法，需持有锁调用并会释放锁；sleep() 不释放锁。'},
{c:'java',t:'多线程',q:'synchronized 修饰实例方法时，锁住的是？',o:['类的 Class 对象','当前实例 this','方法本身','所有实例'],a:1,e:'实例方法锁 this；静态同步方法锁的是类的 Class 对象。'},
{c:'java',t:'多线程',q:'以下哪个类可以实现线程安全的计数自增？',o:['Integer','AtomicInteger','int[]','StringBuilder'],a:1,e:'AtomicInteger 基于 CAS 提供原子操作，如 incrementAndGet()。'},
{c:'java',t:'JVM',q:'new 出来的对象实例主要分配在 JVM 的哪个区域？',o:['栈','堆','程序计数器','方法区'],a:1,e:'对象实例分配在堆上；栈存放局部变量和方法调用帧。'},
{c:'java',t:'JVM',q:'无限递归通常导致哪种错误？',o:['OutOfMemoryError','StackOverflowError','NullPointerException','ClassNotFoundException'],a:1,e:'每次调用压入栈帧，栈深度超限即抛出 StackOverflowError。'},
{c:'java',t:'JVM',q:'Java 8 中，HotSpot 用什么替代了永久代（PermGen）？',o:['元空间 Metaspace','新生代','老年代','直接缓冲区'],a:0,e:'Java 8 移除永久代，类元数据改存放在本地内存中的元空间。'},
{c:'java',t:'JVM',q:'类加载的双亲委派模型中，类加载请求首先交给谁？',o:['当前类加载器自己加载','父类加载器','系统随机选择','最后加载的加载器'],a:1,e:'加载器先委派给父加载器，父加载器无法加载时才由自己加载。'},
{c:'java',t:'JVM',q:'主流 JVM 判断对象是否可回收的主要算法是？',o:['引用计数法','可达性分析','标记计数法','随机采样'],a:1,e:'HotSpot 通过从 GC Roots 出发的可达性分析判断对象是否存活。'},
// ===== SQL =====
{c:'sql',t:'SELECT/WHERE',q:'查询 name 列不为空的记录，正确的写法是？',o:['WHERE name != NULL','WHERE name <> NULL','WHERE name IS NOT NULL','WHERE NOT name = NULL'],a:2,e:'与 NULL 比较须用 IS NULL / IS NOT NULL，= 或 <> 的结果是 UNKNOWN。'},
{c:'sql',t:'SELECT/WHERE',q:'LIKE \'a_%\' 能匹配以下哪个值？',o:['a','ab','ba','空字符串'],a:1,e:'_ 匹配恰好一个字符，% 匹配零或多个字符，所以至少 2 个字符且以 a 开头。'},
{c:'sql',t:'SELECT/WHERE',q:'BETWEEN 10 AND 20 包含的范围是？',o:['10 < x < 20','10 <= x <= 20','10 <= x < 20','10 < x <= 20'],a:1,e:'BETWEEN 是闭区间，包含两端的值。'},
{c:'sql',t:'SELECT/WHERE',q:'去除查询结果中的重复行使用哪个关键字？',o:['UNIQUE','DISTINCT','DIFFERENT','GROUP'],a:1,e:'SELECT DISTINCT 会去除结果集中完全相同的行。'},
{c:'sql',t:'SELECT/WHERE',q:'ORDER BY 默认的排序方式是？',o:['降序 DESC','升序 ASC','按插入顺序','随机'],a:1,e:'ORDER BY 未指定时默认 ASC 升序。'},
{c:'sql',t:'SELECT/WHERE',q:'SELECT 语句各子句的逻辑执行顺序中，最先执行的是？',o:['SELECT','WHERE','FROM','ORDER BY'],a:2,e:'逻辑顺序为 FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY。'},
{c:'sql',t:'SELECT/WHERE',q:'WHERE col NOT IN (1, 2, NULL) 会返回多少行？',o:['返回 col 不等于 1、2 的行','0 行','所有行','报错'],a:1,e:'与 NULL 比较为 UNKNOWN，导致 NOT IN 条件永远不为真，结果为空。'},
{c:'sql',t:'JOIN',q:'INNER JOIN 返回的是？',o:['左表全部行','两表都匹配的行','两表全部行','右表全部行'],a:1,e:'内连接只返回满足连接条件、两边都有匹配的行。'},
{c:'sql',t:'JOIN',q:'LEFT JOIN 时右表无匹配的行，右表列的值为？',o:['0','空字符串','NULL','该行被丢弃'],a:2,e:'左连接保留左表所有行，右表无匹配时列填充 NULL。'},
{c:'sql',t:'JOIN',q:'查找“没有任何订单的客户”，常用写法是？',o:['INNER JOIN 后 WHERE o.id IS NULL','LEFT JOIN orders 后 WHERE o.id IS NULL','CROSS JOIN','RIGHT JOIN 后 WHERE c.id IS NULL'],a:1,e:'左连接后筛选右表主键为 NULL 的行，即左表中无匹配的记录。'},
{c:'sql',t:'JOIN',q:'表 A 有 3 行、表 B 有 4 行，CROSS JOIN 结果有多少行？',o:['7','12','4','3'],a:1,e:'交叉连接是笛卡尔积，行数为 3 × 4 = 12。'},
{c:'sql',t:'JOIN',q:'自连接（self join）通常用于什么场景？',o:['合并两个数据库','查询员工及其上级（同一张表）','删除重复表','创建索引'],a:1,e:'自连接将同一表用不同别名连接，常用于层级关系如员工-经理。'},
{c:'sql',t:'JOIN',q:'LEFT JOIN 中把右表过滤条件写在 WHERE 而不是 ON 中，常见后果是？',o:['没有区别','结果实际上变成类似内连接','语法错误','返回笛卡尔积'],a:1,e:'WHERE 会过滤掉右表为 NULL 的行，左连接保留行的效果丢失。'},
{c:'sql',t:'GROUP BY/HAVING',q:'WHERE 与 HAVING 的主要区别是？',o:['没有区别','WHERE 在分组前过滤，HAVING 在分组后过滤','HAVING 在分组前过滤','WHERE 只能用于 UPDATE'],a:1,e:'WHERE 过滤行且不能用聚合函数，HAVING 过滤分组可使用聚合函数。'},
{c:'sql',t:'GROUP BY/HAVING',q:'COUNT(*) 与 COUNT(col) 的区别是？',o:['完全相同','COUNT(col) 不统计 col 为 NULL 的行','COUNT(*) 不统计 NULL 行','COUNT(col) 会去重'],a:1,e:'COUNT(*) 统计所有行，COUNT(col) 只统计该列非 NULL 的行。'},
{c:'sql',t:'GROUP BY/HAVING',q:'找出员工数超过 5 人的部门，正确的是？',o:['WHERE COUNT(*) > 5','GROUP BY dept HAVING COUNT(*) > 5','HAVING dept > 5','ORDER BY COUNT(*) > 5'],a:1,e:'对分组结果使用聚合条件过滤必须用 HAVING。'},
{c:'sql',t:'GROUP BY/HAVING',q:'AVG(score) 计算时如何处理 NULL 值？',o:['当作 0','忽略 NULL','报错','返回 NULL'],a:1,e:'聚合函数（COUNT(*) 除外）会忽略 NULL，AVG 只对非 NULL 值求平均。'},
{c:'sql',t:'GROUP BY/HAVING',q:'在标准 SQL 中，使用 GROUP BY 时 SELECT 列表中的非聚合列应满足？',o:['可以随意','必须出现在 GROUP BY 中','必须是主键','必须有索引'],a:1,e:'非聚合列需包含在 GROUP BY 中，否则每组的值不确定（标准 SQL 报错）。'},
{c:'sql',t:'子查询',q:'EXISTS 子查询的返回判断依据是？',o:['子查询返回的具体值','子查询是否返回至少一行','子查询返回行数是否大于 1','子查询的第一列是否为真'],a:1,e:'EXISTS 只关心子查询是否有结果行，有则为真。'},
{c:'sql',t:'子查询',q:'查询工资高于平均工资的员工，正确的是？',o:['WHERE salary > AVG(salary)','WHERE salary > (SELECT AVG(salary) FROM emp)','HAVING salary > AVG','WHERE AVG(salary) < salary'],a:1,e:'WHERE 中不能直接用聚合函数，需要用标量子查询计算平均值。'},
{c:'sql',t:'子查询',q:'相关子查询（correlated subquery）的特点是？',o:['只执行一次','引用了外层查询的列','只能出现在 FROM 中','不能使用 WHERE'],a:1,e:'相关子查询依赖外层查询的列，逻辑上对外层每一行都要计算一次。'},
{c:'sql',t:'子查询',q:'使用 = 比较子查询时，子查询返回多行会怎样？',o:['取第一行','报错','取最大值','自动转为 IN'],a:1,e:'= 需要标量子查询，返回多行会报错；多行应使用 IN、ANY 或 ALL。'},
{c:'sql',t:'子查询',q:'salary > ALL (SELECT salary FROM emp WHERE dept=10) 的含义是？',o:['大于其中任意一个','大于其中所有值（即大于最大值）','等于其中某个值','小于最小值'],a:1,e:'> ALL 表示大于子查询结果中的每一个值，相当于大于最大值。'},
{c:'sql',t:'索引',q:'MySQL InnoDB 默认的索引结构是？',o:['哈希表','B+ 树','二叉搜索树','位图'],a:1,e:'InnoDB 使用 B+ 树索引，适合范围查询和排序。'},
{c:'sql',t:'索引',q:'对联合索引 (a, b, c)，以下哪个条件不能利用该索引的最左前缀？',o:['WHERE a = 1','WHERE a = 1 AND b = 2','WHERE b = 2 AND c = 3','WHERE a = 1 AND b = 2 AND c = 3'],a:2,e:'最左前缀原则：缺少最左列 a 时无法用该索引进行查找。'},
{c:'sql',t:'索引',q:'以下哪种写法通常会导致索引失效？',o:['WHERE name = \'Tom\'','WHERE name LIKE \'Tom%\'','WHERE name LIKE \'%Tom\'','WHERE id = 5'],a:2,e:'前导通配符 %Tom 无法利用 B+ 树的有序性，通常导致全表/全索引扫描。'},
{c:'sql',t:'索引',q:'索引的主要缺点是？',o:['降低查询速度','占用空间并降低写入（增删改）性能','不能用于排序','导致数据丢失'],a:1,e:'索引需要额外存储，且每次写入都要维护索引结构。'},
{c:'sql',t:'索引',q:'在 InnoDB 中，查询所需的列全部包含在索引中、无需回表，称为？',o:['聚簇索引','覆盖索引','唯一索引','全文索引'],a:1,e:'覆盖索引可直接从二级索引获取数据，避免回表查询主键索引。'},
{c:'sql',t:'事务',q:'ACID 中的 “I” 代表？',o:['完整性 Integrity','隔离性 Isolation','索引 Index','不可变 Immutable'],a:1,e:'ACID 即原子性、一致性、隔离性、持久性。'},
{c:'sql',t:'事务',q:'撤销当前事务中所有未提交修改的语句是？',o:['COMMIT','ROLLBACK','SAVEPOINT','REVOKE'],a:1,e:'ROLLBACK 回滚事务；COMMIT 提交使修改永久生效。'},
{c:'sql',t:'事务',q:'MySQL InnoDB 默认的事务隔离级别是？',o:['READ UNCOMMITTED','READ COMMITTED','REPEATABLE READ','SERIALIZABLE'],a:2,e:'InnoDB 默认为可重复读 REPEATABLE READ。'},
{c:'sql',t:'事务',q:'读到其他事务尚未提交的数据，称为？',o:['脏读','不可重复读','幻读','丢失更新'],a:0,e:'脏读只会在 READ UNCOMMITTED 级别发生。'},
{c:'sql',t:'事务',q:'哪个隔离级别能避免脏读、不可重复读和幻读？',o:['READ UNCOMMITTED','READ COMMITTED','REPEATABLE READ','SERIALIZABLE'],a:3,e:'SERIALIZABLE 让事务串行化执行，可避免所有这三种并发问题。'},
{c:'sql',t:'事务',q:'同一事务中两次读取同一行，结果因其他事务提交的修改而不同，称为？',o:['脏读','不可重复读','幻读','死锁'],a:1,e:'不可重复读针对同一行被修改；幻读针对范围内行数变化。'},
];
QUESTIONS.forEach((q,i)=>q.id=i);
