// 题库（自动生成）：id 稳定唯一，格式 科目-级别-序号；新增题目请追加新 id，不要复用旧 id
// {id, c:科目, l:级别 1初级/2中级/3高级, q:题目, o:选项, a:正确选项下标, e:解析}
const QUESTIONS = [
{"id":"java-1-001","c":"java","l":1,"q":"Java 中 int 类型占用多少位？","o":["32 位","取决于平台","16 位","64 位"],"a":0,"e":"Java 的 int 固定为 32 位有符号整数，与平台无关。"},
{"id":"java-1-002","c":"java","l":1,"q":"以下哪个不是 Java 的基本数据类型？","o":["String","byte","boolean","char"],"a":0,"e":"String 是引用类型（类），不属于 8 种基本类型。"},
{"id":"java-1-003","c":"java","l":1,"q":"表达式 10 / 4 在 Java 中的结果是？","o":["2.5","2.0","2","3"],"a":2,"e":"两个 int 相除为整数除法，结果截断为 2。"},
{"id":"java-1-004","c":"java","l":1,"q":"对于两个 String 对象，== 比较的是什么？","o":["哈希值","字符串内容","长度","引用是否指向同一对象"],"a":3,"e":"== 比较引用；比较内容应使用 equals()。"},
{"id":"java-1-005","c":"java","l":1,"q":"单线程中频繁拼接字符串，最推荐使用？","o":["String","StringBuilder","char","StringBuffer"],"a":1,"e":"StringBuilder 可变且无同步开销；StringBuffer 线程安全但较慢。"},
{"id":"java-1-006","c":"java","l":1,"q":"Java 方法参数的传递方式是？","o":["基本类型按值，对象按引用","由编译器决定","总是按值传递","总是按引用传递"],"a":2,"e":"Java 只有值传递；对象参数传递的是引用的副本。"},
{"id":"java-1-007","c":"java","l":1,"q":"long 类型占用多少字节？","o":["4 字节","8 字节","16 字节","2 字节"],"a":1,"e":"long 为 64 位，即 8 字节。"},
{"id":"java-1-008","c":"java","l":1,"q":"char 类型在 Java 中占用多少位？","o":["取决于编码","16 位","32 位","8 位"],"a":1,"e":"Java 的 char 是 16 位无符号 UTF-16 码元。"},
{"id":"java-1-009","c":"java","l":1,"q":"boolean 类型变量作为类的成员变量时默认值是？","o":["false","true","null","0"],"a":0,"e":"boolean 成员变量默认初始化为 false。"},
{"id":"java-1-010","c":"java","l":1,"q":"int 类型成员变量的默认值是？","o":["未定义，必须赋值","-1","null","0"],"a":3,"e":"数值类型成员变量默认值为 0；局部变量则必须先赋值。"},
{"id":"java-1-011","c":"java","l":1,"q":"局部变量未初始化就使用，会发生什么？","o":["运行时异常","默认为 0","默认为 null","编译错误"],"a":3,"e":"Java 要求局部变量在使用前必须明确赋值。"},
{"id":"java-1-012","c":"java","l":1,"q":"float f = 3.14; 这行代码会怎样？","o":["运行时异常","正常编译","编译错误","自动截断为 3"],"a":2,"e":"3.14 是 double 字面量，需写成 3.14f 或强制转换。"},
{"id":"java-1-013","c":"java","l":1,"q":"表达式 5 % 3 的结果是？","o":["0","1.67","1","2"],"a":3,"e":"% 为取余运算，5 除以 3 余 2。"},
{"id":"java-1-014","c":"java","l":1,"q":"表达式 -7 % 3 在 Java 中的结果是？","o":["-1","2","-2","1"],"a":0,"e":"Java 取余结果的符号与被除数相同。"},
{"id":"java-1-015","c":"java","l":1,"q":"int i = 5; int j = i++; 执行后 j 的值是？","o":["4","6","5","0"],"a":2,"e":"i++ 先取值后自增，所以 j 为 5，i 为 6。"},
{"id":"java-1-016","c":"java","l":1,"q":"int i = 5; int j = ++i; 执行后 j 的值是？","o":["0","6","7","5"],"a":1,"e":"++i 先自增后取值，所以 j 为 6。"},
{"id":"java-1-017","c":"java","l":1,"q":"(int) 3.99 的结果是？","o":["4","3.99","3","编译错误"],"a":2,"e":"double 强转 int 直接截断小数部分。"},
{"id":"java-1-018","c":"java","l":1,"q":"Math.round(-2.5) 的结果是？","o":["2","-2.5","-2","-3"],"a":2,"e":"Math.round 等价于 floor(x + 0.5)，-2.5 + 0.5 = -2。"},
{"id":"java-1-019","c":"java","l":1,"q":"\"a\" + 1 + 2 的结果是？","o":["\"a3\"","\"3a\"","\"a12\"","编译错误"],"a":2,"e":"从左到右计算，字符串与数字相连变为字符串拼接。"},
{"id":"java-1-020","c":"java","l":1,"q":"1 + 2 + \"a\" 的结果是？","o":["\"3a\"","\"12a\"","编译错误","\"a3\""],"a":0,"e":"先计算 1 + 2 = 3，再与 \"a\" 拼接。"},
{"id":"java-1-021","c":"java","l":1,"q":"以下哪个是合法的 Java 标识符？","o":["_count","class","2name","my-var"],"a":0,"e":"标识符不能以数字开头、不能是关键字、不能含减号。"},
{"id":"java-1-022","c":"java","l":1,"q":"Java 程序的入口方法签名是？","o":["public void main()","static int main(String args)","public main(String[] args)","public static void main(String[] args)"],"a":3,"e":"JVM 从 public static void main(String[]) 开始执行。"},
{"id":"java-1-023","c":"java","l":1,"q":"数组 int[] a = new int[5]; a 的最大合法下标是？","o":["5","4","6","0"],"a":1,"e":"数组下标从 0 开始，长度为 5 时最大下标为 4。"},
{"id":"java-1-024","c":"java","l":1,"q":"访问数组越界下标会抛出？","o":["NullPointerException","IllegalArgumentException","ArrayIndexOutOfBoundsException","编译错误"],"a":2,"e":"越界访问在运行时抛出 ArrayIndexOutOfBoundsException。"},
{"id":"java-1-025","c":"java","l":1,"q":"获取数组长度的正确写法是？","o":["arr.length()","arr.size()","arr.getLength()","arr.length"],"a":3,"e":"数组的 length 是属性，不是方法。"},
{"id":"java-1-026","c":"java","l":1,"q":"获取 String 长度的正确写法是？","o":["s.length()","s.size()","s.count()","s.length"],"a":0,"e":"String 的长度通过 length() 方法获取。"},
{"id":"java-1-027","c":"java","l":1,"q":"switch 语句中漏写 break 会怎样？","o":["自动跳出","继续执行下一个 case（穿透）","抛出异常","编译错误"],"a":1,"e":"没有 break 时会穿透执行后续 case 分支。"},
{"id":"java-1-028","c":"java","l":1,"q":"从 Java 7 开始，switch 可以使用以下哪种类型？","o":["boolean","String","double","long"],"a":1,"e":"Java 7 起 switch 支持 String；不支持 long、float、double、boolean。"},
{"id":"java-1-029","c":"java","l":1,"q":"continue 语句的作用是？","o":["跳过本次循环剩余部分，进入下一次循环","退出方法","退出整个循环","跳到程序开头"],"a":0,"e":"continue 结束本次迭代；break 才是退出循环。"},
{"id":"java-1-030","c":"java","l":1,"q":"do-while 循环至少执行几次？","o":["不确定","0 次","2 次","1 次"],"a":3,"e":"do-while 先执行循环体再判断条件，所以至少执行一次。"},
{"id":"java-1-031","c":"java","l":1,"q":"以下哪个关键字用于定义常量？","o":["static","final","const","define"],"a":1,"e":"Java 用 final 定义常量；const 是保留字但未使用。"},
{"id":"java-1-032","c":"java","l":1,"q":"static 修饰的成员变量属于？","o":["包","方法","类本身，所有实例共享","每个实例各一份"],"a":2,"e":"静态变量属于类，只有一份，被所有实例共享。"},
{"id":"java-1-033","c":"java","l":1,"q":"静态方法中能否直接访问非静态成员变量？","o":["只能读不能写","不能","只能在 main 中","能"],"a":1,"e":"静态方法没有 this，不能直接访问实例成员。"},
{"id":"java-1-034","c":"java","l":1,"q":"关于 String 的说法，正确的是？","o":["String 被 final 修饰且不可变","String 是可变的","String 是基本类型","String 不能作为 HashMap 的键"],"a":0,"e":"String 类是 final 的，对象创建后内容不能修改。"},
{"id":"java-1-035","c":"java","l":1,"q":"\"hello\".substring(1, 3) 的结果是？","o":["\"hel\"","\"ell\"","\"he\"","\"el\""],"a":3,"e":"substring 截取 [begin, end)，即下标 1 到 2。"},
{"id":"java-1-036","c":"java","l":1,"q":"\"Java\".charAt(0) 返回？","o":["\"J\"","74 的字符串","'J'","'a'"],"a":2,"e":"charAt 返回指定下标的 char。"},
{"id":"java-1-037","c":"java","l":1,"q":"\"abc\".equals(\"ABC\") 的结果是？","o":["true","false","编译错误","抛出异常"],"a":1,"e":"equals 区分大小写；忽略大小写用 equalsIgnoreCase。"},
{"id":"java-1-038","c":"java","l":1,"q":"\"a,b,c\".split(\",\") 返回的数组长度是？","o":["3","2","1","5"],"a":0,"e":"按逗号分割得到 \"a\"、\"b\"、\"c\" 三个元素。"},
{"id":"java-1-039","c":"java","l":1,"q":"\" hi \".trim() 的结果是？","o":["\" hi\"","\"hi \"","\"hi\"","\" hi \""],"a":2,"e":"trim() 去除首尾空白字符。"},
{"id":"java-1-040","c":"java","l":1,"q":"将字符串 \"123\" 转为 int 的方法是？","o":["Integer.toString(\"123\")","String.toInt(\"123\")","(int) \"123\"","Integer.parseInt(\"123\")"],"a":3,"e":"Integer.parseInt 将字符串解析为 int。"},
{"id":"java-1-041","c":"java","l":1,"q":"Integer.parseInt(\"abc\") 会抛出？","o":["返回 0","NumberFormatException","ClassCastException","NullPointerException"],"a":1,"e":"无法解析的字符串会抛出 NumberFormatException。"},
{"id":"java-1-042","c":"java","l":1,"q":"Integer a = 127, b = 127; a == b 的结果是？","o":["编译错误","运行时异常","false","true"],"a":3,"e":"Integer 缓存 -128~127，自动装箱返回同一对象。"},
{"id":"java-1-043","c":"java","l":1,"q":"Integer a = 128, b = 128; a == b 的结果（默认配置）是？","o":["编译错误","true","false","运行时异常"],"a":2,"e":"128 超出默认缓存范围，装箱得到两个不同对象。"},
{"id":"java-1-044","c":"java","l":1,"q":"int 自动转换为 Integer 的过程称为？","o":["自动装箱","强制转换","自动拆箱","泛型擦除"],"a":0,"e":"基本类型转为包装类型称为装箱，反之为拆箱。"},
{"id":"java-1-045","c":"java","l":1,"q":"Integer x = null; int y = x; 运行时会怎样？","o":["抛出 NullPointerException","y 为 null","y 为 0","编译错误"],"a":0,"e":"自动拆箱时对 null 调用 intValue() 导致空指针。"},
{"id":"java-1-046","c":"java","l":1,"q":"Java 中一个类可以直接继承几个父类？","o":["0 个","2 个","任意多个","1 个"],"a":3,"e":"Java 类只支持单继承，但可实现多个接口。"},
{"id":"java-1-047","c":"java","l":1,"q":"所有 Java 类的根父类是？","o":["Object","System","Base","Class"],"a":0,"e":"未显式继承的类默认继承 java.lang.Object。"},
{"id":"java-1-048","c":"java","l":1,"q":"创建对象使用的关键字是？","o":["create","alloc","make","new"],"a":3,"e":"new 关键字在堆上创建对象并调用构造方法。"},
{"id":"java-1-049","c":"java","l":1,"q":"构造方法的特点是？","o":["必须有返回值","与类同名且没有返回值类型","名字可以任意","必须是 static"],"a":1,"e":"构造方法与类同名、无返回值类型，用于初始化对象。"},
{"id":"java-1-050","c":"java","l":1,"q":"类中没有定义任何构造方法时会怎样？","o":["必须用 static 创建","编译错误","无法创建对象","编译器提供一个默认无参构造方法"],"a":3,"e":"没有显式构造方法时编译器自动生成无参构造方法。"},
{"id":"java-1-051","c":"java","l":1,"q":"this 关键字指代的是？","o":["静态成员","父类对象","当前对象","当前类的 Class"],"a":2,"e":"this 是当前实例的引用。"},
{"id":"java-1-052","c":"java","l":1,"q":"在子类构造方法中调用父类构造方法使用？","o":["this(...)","parent(...)","super(...)","base(...)"],"a":2,"e":"super(...) 必须是构造方法的第一条语句。"},
{"id":"java-1-053","c":"java","l":1,"q":"private 成员可以被谁访问？","o":["本类和子类","同包类","所有类","仅本类"],"a":3,"e":"private 访问范围最小，只在本类内部可见。"},
{"id":"java-1-054","c":"java","l":1,"q":"没有任何访问修饰符（默认）的成员可被谁访问？","o":["仅本类","仅子类","所有类","同一个包中的类"],"a":3,"e":"默认（包私有）访问权限限于同包。"},
{"id":"java-1-055","c":"java","l":1,"q":"protected 成员可以被谁访问？","o":["仅本类","仅同包类","所有类","同包类及其他包中的子类"],"a":3,"e":"protected 允许同包访问和不同包子类访问。"},
{"id":"java-1-056","c":"java","l":1,"q":"方法重载（Overload）的判定依据是？","o":["返回值类型不同","抛出异常不同","访问修饰符不同","参数列表不同"],"a":3,"e":"重载要求同名方法参数列表不同，仅返回值不同不构成重载。"},
{"id":"java-1-057","c":"java","l":1,"q":"方法重写（Override）要求？","o":["参数列表不同","方法名不同","方法名和参数列表与父类相同","必须是 static 方法"],"a":2,"e":"重写要求签名相同，返回类型相同或为其子类型。"},
{"id":"java-1-058","c":"java","l":1,"q":"被 final 修饰的类有什么特点？","o":["不能被实例化","不能有构造器","所有方法都是静态的","不能被继承"],"a":3,"e":"final 类不可继承，如 String，但可正常实例化。"},
{"id":"java-1-059","c":"java","l":1,"q":"被 final 修饰的方法有什么特点？","o":["不能有参数","不能被子类重写","必须是静态的","不能被调用"],"a":1,"e":"final 方法禁止子类重写。"},
{"id":"java-1-060","c":"java","l":1,"q":"关于抽象类，正确的是？","o":["可以有构造方法","可以直接 new 实例","不能有普通方法","必须包含抽象方法"],"a":0,"e":"抽象类可有构造方法供子类调用，但不能直接实例化。"},
{"id":"java-1-061","c":"java","l":1,"q":"含有抽象方法的类必须声明为？","o":["static 类","interface","abstract 类","final 类"],"a":2,"e":"有抽象方法的类必须是抽象类。"},
{"id":"java-1-062","c":"java","l":1,"q":"类实现接口使用的关键字是？","o":["extends","implements","inherits","uses"],"a":1,"e":"类用 implements 实现接口，用 extends 继承类。"},
{"id":"java-1-063","c":"java","l":1,"q":"接口之间的继承使用哪个关键字？","o":["inherits","implements","super","extends"],"a":3,"e":"接口可以用 extends 继承一个或多个接口。"},
{"id":"java-1-064","c":"java","l":1,"q":"接口中声明的变量默认是？","o":["public static final","普通实例变量","private","protected"],"a":0,"e":"接口字段隐式为 public static final 常量。"},
{"id":"java-1-065","c":"java","l":1,"q":"多态的前提不包括？","o":["子类必须是 final 的","继承或实现","方法重写","父类引用指向子类对象"],"a":0,"e":"多态需要继承、重写和向上转型，与 final 无关。"},
{"id":"java-1-066","c":"java","l":1,"q":"Animal a = new Dog(); a.speak() 调用的是？","o":["编译错误","随机","Animal 的 speak","Dog 的 speak（若 Dog 重写）"],"a":3,"e":"实例方法调用是动态绑定，取决于运行时实际对象类型。"},
{"id":"java-1-067","c":"java","l":1,"q":"判断对象是否为某类型的实例使用？","o":["sizeof","isType","typeof","instanceof"],"a":3,"e":"instanceof 用于运行时类型检查。"},
{"id":"java-1-068","c":"java","l":1,"q":"不合法的向下转型会抛出？","o":["ClassCastException","NullPointerException","编译错误","IllegalStateException"],"a":0,"e":"运行时实际类型不匹配时抛出 ClassCastException。"},
{"id":"java-1-069","c":"java","l":1,"q":"重写 equals() 时通常还必须重写？","o":["finalize()","toString()","hashCode()","clone()"],"a":2,"e":"相等的对象必须有相同哈希码，否则在哈希集合中出错。"},
{"id":"java-1-070","c":"java","l":1,"q":"Object 类的 toString() 默认返回？","o":["对象所有字段","null","类名@哈希码的十六进制","空字符串"],"a":2,"e":"默认格式为 getClass().getName() + \"@\" + 十六进制哈希码。"},
{"id":"java-1-071","c":"java","l":1,"q":"封装的主要做法是？","o":["所有字段设为 public","使用多继承","所有方法设为 static","字段私有化并提供 getter/setter"],"a":3,"e":"封装隐藏内部状态，通过公共方法受控访问。"},
{"id":"java-1-072","c":"java","l":1,"q":"包的作用不包括？","o":["组织类","控制访问权限","提升运行速度","避免命名冲突"],"a":2,"e":"包用于命名空间和访问控制，与运行速度无关。"},
{"id":"java-1-073","c":"java","l":1,"q":"引入其他包中的类使用？","o":["include","require","import","using"],"a":2,"e":"Java 使用 import 语句导入类。"},
{"id":"java-1-074","c":"java","l":1,"q":"java.lang 包中的类需要 import 吗？","o":["只有 String 需要","需要","视 JDK 版本而定","不需要，自动导入"],"a":3,"e":"java.lang 包被编译器默认导入。"},
{"id":"java-1-075","c":"java","l":1,"q":"以下哪个集合不允许重复元素？","o":["Vector","HashSet","ArrayList","LinkedList"],"a":1,"e":"Set 接口的实现不允许重复元素。"},
{"id":"java-1-076","c":"java","l":1,"q":"ArrayList 按下标 get(i) 的时间复杂度是？","o":["O(1)","O(n log n)","O(log n)","O(n)"],"a":0,"e":"ArrayList 基于数组，随机访问为 O(1)。"},
{"id":"java-1-077","c":"java","l":1,"q":"HashMap 是否允许 null 键？","o":["允许多个 null 键","允许一个 null 键","不允许","仅 Java 8 前允许"],"a":1,"e":"HashMap 允许一个 null 键和多个 null 值。"},
{"id":"java-1-078","c":"java","l":1,"q":"List、Set、Map 中，哪个不继承 Collection 接口？","o":["List","Set","都继承","Map"],"a":3,"e":"Map 是独立的接口体系，不继承 Collection。"},
{"id":"java-1-079","c":"java","l":1,"q":"向 HashMap 中 put 已存在的键会怎样？","o":["保留旧值","覆盖旧值并返回旧值","创建重复键","抛出异常"],"a":1,"e":"相同键 put 会替换值，并返回之前的值。"},
{"id":"java-1-080","c":"java","l":1,"q":"需要按插入顺序遍历的 Map 是？","o":["HashMap","LinkedHashMap","Hashtable","TreeMap"],"a":1,"e":"LinkedHashMap 维护双向链表，默认保持插入顺序。"},
{"id":"java-1-081","c":"java","l":1,"q":"需要按键排序的 Map 是？","o":["HashMap","LinkedHashMap","IdentityHashMap","TreeMap"],"a":3,"e":"TreeMap 基于红黑树，按键自然顺序或 Comparator 排序。"},
{"id":"java-1-082","c":"java","l":1,"q":"集合中只能存放什么类型？","o":["任意类型包括 int","基本类型","引用类型（对象）","只能存 String"],"a":2,"e":"集合存放对象，int 等会自动装箱成包装类。"},
{"id":"java-1-083","c":"java","l":1,"q":"遍历 List 时最简洁的写法是？","o":["增强 for 循环 for (T x : list)","switch","while (true)","goto"],"a":0,"e":"增强 for 循环可遍历数组和 Iterable。"},
{"id":"java-1-084","c":"java","l":1,"q":"Arrays.sort(int[]) 的作用是？","o":["对数组降序排序","复制数组","打乱数组","对数组升序排序"],"a":3,"e":"Arrays.sort 对基本类型数组升序排序。"},
{"id":"java-1-085","c":"java","l":1,"q":"以下哪个是受检异常（checked）？","o":["IOException","ArithmeticException","NullPointerException","IllegalArgumentException"],"a":0,"e":"IOException 不是 RuntimeException 子类，必须捕获或声明。"},
{"id":"java-1-086","c":"java","l":1,"q":"整数除以 0（如 1 / 0）会抛出？","o":["ArithmeticException","返回 Infinity","编译错误","NumberFormatException"],"a":0,"e":"整数除零抛出 ArithmeticException；浮点除零得到 Infinity。"},
{"id":"java-1-087","c":"java","l":1,"q":"1.0 / 0 的结果是？","o":["抛出 ArithmeticException","0","Infinity","NaN"],"a":2,"e":"浮点除以零得到正无穷 Infinity。"},
{"id":"java-1-088","c":"java","l":1,"q":"try 中执行了 return，finally 会执行吗？","o":["不会","编译错误","会，在返回前执行","只有异常时执行"],"a":2,"e":"finally 在方法返回前执行，除非 JVM 退出。"},
{"id":"java-1-089","c":"java","l":1,"q":"Error 和 Exception 的共同父类是？","o":["RuntimeException","Serializable","Object","Throwable"],"a":3,"e":"Throwable 是所有错误和异常的父类。"},
{"id":"java-1-090","c":"java","l":1,"q":"在方法签名中声明可能抛出的异常使用？","o":["try","throws","catch","throw"],"a":1,"e":"throws 用于声明；throw 用于实际抛出异常对象。"},
{"id":"java-1-091","c":"java","l":1,"q":"主动抛出一个异常对象使用？","o":["raise","error","throws","throw"],"a":3,"e":"throw new XxxException() 抛出异常实例。"},
{"id":"java-1-092","c":"java","l":1,"q":"多个 catch 块时，子类异常应放在？","o":["只能有一个 catch","任意位置","父类异常之后","父类异常之前"],"a":3,"e":"若父类异常在前，子类 catch 不可达，编译报错。"},
{"id":"java-1-093","c":"java","l":1,"q":"对 null 引用调用方法会抛出？","o":["ClassCastException","IllegalStateException","NullPointerException","编译错误"],"a":2,"e":"对 null 调用实例方法会在运行时抛出空指针异常。"},
{"id":"java-1-094","c":"java","l":1,"q":"启动新线程应调用 Thread 的？","o":["start()","run()","execute()","init()"],"a":0,"e":"start() 创建新线程并调用 run()；直接调用 run() 只是普通调用。"},
{"id":"java-1-095","c":"java","l":1,"q":"new 出来的对象实例主要分配在？","o":["程序计数器","寄存器","堆","栈"],"a":2,"e":"对象实例分配在堆上；局部变量在栈帧中。"},
{"id":"java-1-096","c":"java","l":1,"q":"Java 源文件编译后生成什么文件？","o":[".exe 文件",".class 字节码文件",".dll 文件",".obj 文件"],"a":1,"e":"javac 将 .java 编译为 .class 字节码，由 JVM 执行。"},
{"id":"java-1-097","c":"java","l":1,"q":"Java “一次编写，到处运行”依靠的是？","o":["JVM","浏览器","编译器优化","操作系统"],"a":0,"e":"字节码在各平台的 JVM 上运行，实现跨平台。"},
{"id":"java-1-098","c":"java","l":1,"q":"JDK 与 JRE 的关系是？","o":["两者无关","JDK 包含 JRE 和开发工具","JRE 包含 JDK","JDK 只包含 JVM"],"a":1,"e":"JDK 提供 javac 等开发工具，并包含运行环境。"},
{"id":"java-1-099","c":"java","l":1,"q":"Java 中对象的内存回收由谁负责？","o":["程序员手动 free","垃圾回收器 GC","编译器","操作系统"],"a":1,"e":"Java 由 GC 自动回收不再被引用的对象。"},
{"id":"java-1-100","c":"java","l":1,"q":"System.out.println 中的 out 是？","o":["包名","关键字","方法","System 类的静态 PrintStream 字段"],"a":3,"e":"out 是 System 类的 public static final PrintStream。"},
{"id":"java-2-001","c":"java","l":2,"q":"用增强 for 遍历 ArrayList 时直接调用 list.remove(obj)，通常会抛出？","o":["IndexOutOfBoundsException","NullPointerException","ConcurrentModificationException","ClassCastException"],"a":2,"e":"结构修改触发 fail-fast；应使用 Iterator.remove() 或 removeIf()。"},
{"id":"java-2-002","c":"java","l":2,"q":"多线程环境下推荐使用的高并发 Map 是？","o":["ConcurrentHashMap","HashMap","LinkedHashMap","TreeMap"],"a":0,"e":"ConcurrentHashMap 使用细粒度锁和 CAS，并发性能优于 Hashtable。"},
{"id":"java-2-003","c":"java","l":2,"q":"ArrayList 默认构造后首次添加元素时的容量是？","o":["8","16","1","10"],"a":3,"e":"无参构造时为空数组，首次 add 时扩容到默认容量 10。"},
{"id":"java-2-004","c":"java","l":2,"q":"ArrayList 扩容时新容量大约是原来的？","o":["1.5 倍","固定加 10","2 倍","1.25 倍"],"a":0,"e":"扩容公式为 oldCapacity + (oldCapacity >> 1)。"},
{"id":"java-2-005","c":"java","l":2,"q":"HashMap 的默认初始容量是？","o":["16","10","32","8"],"a":0,"e":"HashMap 默认容量 16，负载因子 0.75。"},
{"id":"java-2-006","c":"java","l":2,"q":"HashMap 的默认负载因子是？","o":["0.5","0.8","1.0","0.75"],"a":3,"e":"0.75 在时间与空间开销之间取得平衡。"},
{"id":"java-2-007","c":"java","l":2,"q":"HashMap 的容量为什么总是 2 的幂？","o":["为了线程安全","节省内存","可以用 (n-1) & hash 代替取模，且分布均匀","JVM 强制要求"],"a":2,"e":"2 的幂使按位与等价于取模，计算更快。"},
{"id":"java-2-008","c":"java","l":2,"q":"Java 8 中 HashMap 链表在什么情况下转为红黑树？","o":["容量超过 1024","任何冲突时","链表长度达到 8 且数组容量不小于 64","链表长度达到 4"],"a":2,"e":"阈值 TREEIFY_THRESHOLD=8，且容量需 ≥64，否则优先扩容。"},
{"id":"java-2-009","c":"java","l":2,"q":"LinkedList 底层的数据结构是？","o":["双向链表","动态数组","红黑树","单向链表"],"a":0,"e":"LinkedList 是双向链表，同时实现了 List 和 Deque。"},
{"id":"java-2-010","c":"java","l":2,"q":"在 LinkedList 头部插入元素的时间复杂度是？","o":["O(log n)","O(1)","O(n²)","O(n)"],"a":1,"e":"链表头插只需修改指针。"},
{"id":"java-2-011","c":"java","l":2,"q":"HashSet 底层是基于什么实现的？","o":["链表","数组列表","HashMap","TreeMap"],"a":2,"e":"HashSet 内部使用 HashMap 的键存储元素。"},
{"id":"java-2-012","c":"java","l":2,"q":"TreeSet 中的元素必须满足？","o":["重写 toString","是 String 类型","可比较（实现 Comparable 或提供 Comparator）","实现 Serializable"],"a":2,"e":"TreeSet 需要排序，元素必须可比较。"},
{"id":"java-2-013","c":"java","l":2,"q":"Comparable 与 Comparator 的区别是？","o":["两者完全相同","Comparable 是类自身的自然排序，Comparator 是外部比较器","Comparator 只能比较数字","Comparable 在 java.util 包中"],"a":1,"e":"Comparable 实现 compareTo；Comparator 实现 compare，可定义多种排序。"},
{"id":"java-2-014","c":"java","l":2,"q":"Arrays.asList(1,2,3) 返回的 List 调用 add() 会怎样？","o":["编译错误","返回 false","抛出 UnsupportedOperationException","正常添加"],"a":2,"e":"它返回固定大小的列表，不支持增删。"},
{"id":"java-2-015","c":"java","l":2,"q":"List.of(1, 2, 3)（Java 9+）返回的列表特点是？","o":["可变","线程不安全可扩容","不可变，修改抛异常","允许 null"],"a":2,"e":"List.of 返回不可变列表，且不允许 null 元素。"},
{"id":"java-2-016","c":"java","l":2,"q":"Iterator 接口中用于安全删除当前元素的方法是？","o":["delete()","clear()","remove()","drop()"],"a":2,"e":"迭代时用 Iterator.remove() 不会触发 ConcurrentModificationException。"},
{"id":"java-2-017","c":"java","l":2,"q":"Queue 接口中，队列为空时 poll() 的行为是？","o":["阻塞等待","返回 null","抛出异常","返回 0"],"a":1,"e":"poll() 返回 null，而 remove() 会抛出 NoSuchElementException。"},
{"id":"java-2-018","c":"java","l":2,"q":"PriorityQueue 默认是？","o":["大顶堆","小顶堆","栈","先进先出队列"],"a":1,"e":"PriorityQueue 默认按自然顺序，队首为最小元素。"},
{"id":"java-2-019","c":"java","l":2,"q":"推荐用作栈的类是？","o":["TreeSet","Stack","ArrayDeque","Vector"],"a":2,"e":"ArrayDeque 比遗留的同步类 Stack 性能更好。"},
{"id":"java-2-020","c":"java","l":2,"q":"Collections.unmodifiableList(list) 返回的视图有什么特点？","o":["会清空原列表","完全独立的副本","不能通过它修改，但原列表修改会反映出来","线程安全的可变列表"],"a":2,"e":"它是只读视图，底层列表变化仍可见。"},
{"id":"java-2-021","c":"java","l":2,"q":"List<Integer> list 中 list.remove(1) 删除的是？","o":["所有值为 1 的元素","值为 1 的元素","编译错误","下标为 1 的元素"],"a":3,"e":"int 参数匹配 remove(int index)；删除值需 remove(Integer.valueOf(1))。"},
{"id":"java-2-022","c":"java","l":2,"q":"泛型的主要作用是？","o":["实现多继承","提升运行速度","编译期类型检查并减少强制转换","减少内存占用"],"a":2,"e":"泛型让类型错误在编译期暴露，并免去显式强转。"},
{"id":"java-2-023","c":"java","l":2,"q":"List<String> 能赋值给 List<Object> 吗？","o":["不能，泛型不协变","只在运行时能","只在 Java 8 后能","能"],"a":0,"e":"即使 String 是 Object 子类，List<String> 也不是 List<Object> 的子类型。"},
{"id":"java-2-024","c":"java","l":2,"q":"<? extends Number> 表示？","o":["只能是 Number","Number 或其子类型","任意类型","Number 或其父类型"],"a":1,"e":"上界通配符，适合读取（生产者）。"},
{"id":"java-2-025","c":"java","l":2,"q":"<? super Integer> 表示？","o":["任意数字","Integer 或其子类型","只能是 Integer","Integer 或其父类型"],"a":3,"e":"下界通配符，适合写入（消费者）。"},
{"id":"java-2-026","c":"java","l":2,"q":"Java 泛型在运行时的类型信息通常会？","o":["转为字符串","报错","完整保留","被擦除"],"a":3,"e":"类型擦除使泛型参数在运行时被替换为上界（通常是 Object）。"},
{"id":"java-2-027","c":"java","l":2,"q":"以下哪个写法是非法的？","o":["List<T> list","<T> void f(T t)","T[] 作为参数类型","new T()（T 为类型参数）"],"a":3,"e":"类型擦除后无法得知 T 的具体类型，因此不能直接 new T()。"},
{"id":"java-2-028","c":"java","l":2,"q":"Java 8 的 Lambda 表达式可以用于实现？","o":["函数式接口（只有一个抽象方法的接口）","任意抽象类","有多个抽象方法的接口","任意类"],"a":0,"e":"Lambda 只能赋给函数式接口类型。"},
{"id":"java-2-029","c":"java","l":2,"q":"@FunctionalInterface 注解的作用是？","o":["让编译器检查接口是否只有一个抽象方法","使接口线程安全","自动生成实现类","提升性能"],"a":0,"e":"它是编译期检查，不加也可以作为函数式接口使用。"},
{"id":"java-2-030","c":"java","l":2,"q":"Lambda 中引用的外部局部变量必须是？","o":["public","final 或事实上 final","volatile","static"],"a":1,"e":"被捕获的局部变量不能被重新赋值。"},
{"id":"java-2-031","c":"java","l":2,"q":"Stream 的中间操作有什么特点？","o":["立即执行","会修改源集合","只能调用一次","惰性执行，直到终端操作才计算"],"a":3,"e":"filter、map 等中间操作是惰性的。"},
{"id":"java-2-032","c":"java","l":2,"q":"以下哪个是 Stream 的终端操作？","o":["map()","sorted()","collect()","filter()"],"a":2,"e":"collect、forEach、count 等终端操作触发计算。"},
{"id":"java-2-033","c":"java","l":2,"q":"Stream 可以被消费几次？","o":["1 次","取决于数据源","2 次","任意次"],"a":0,"e":"Stream 只能消费一次，重复使用抛出 IllegalStateException。"},
{"id":"java-2-034","c":"java","l":2,"q":"map 与 flatMap 的区别是？","o":["两者相同","flatMap 将每个元素映射为流并扁平化合并","map 会去重","flatMap 只能用于数字"],"a":1,"e":"flatMap 适合把嵌套集合展开为单层流。"},
{"id":"java-2-035","c":"java","l":2,"q":"Optional 的主要用途是？","o":["显式表达可能为空的返回值","实现序列化","提高性能","替代所有集合"],"a":0,"e":"Optional 用于减少 null 判断和 NPE。"},
{"id":"java-2-036","c":"java","l":2,"q":"Optional.of(null) 会怎样？","o":["编译错误","抛出 NullPointerException","返回 null","返回空 Optional"],"a":1,"e":"允许 null 时应使用 Optional.ofNullable。"},
{"id":"java-2-037","c":"java","l":2,"q":"方法引用 String::length 等价于？","o":["s -> String.length","s -> s.length()","x -> x.size()","() -> length()"],"a":1,"e":"这是任意对象的实例方法引用。"},
{"id":"java-2-038","c":"java","l":2,"q":"Java 8 引入的新日期时间 API 所在包是？","o":["java.util.Date","java.time","java.text","java.sql"],"a":1,"e":"java.time 提供 LocalDate 等不可变、线程安全的类。"},
{"id":"java-2-039","c":"java","l":2,"q":"try-with-resources 要求资源实现？","o":["AutoCloseable","Serializable","Iterable","Runnable"],"a":0,"e":"块结束时自动调用 close()，Closeable 是 AutoCloseable 的子接口。"},
{"id":"java-2-040","c":"java","l":2,"q":"try-with-resources 中多个资源的关闭顺序是？","o":["不会关闭","随机","与声明顺序相同","与声明顺序相反"],"a":3,"e":"资源按声明的逆序关闭。"},
{"id":"java-2-041","c":"java","l":2,"q":"自定义受检异常通常继承？","o":["RuntimeException","Error","Exception","Throwable 的子类 Error"],"a":2,"e":"继承 Exception（非 RuntimeException）即为受检异常。"},
{"id":"java-2-042","c":"java","l":2,"q":"自定义非受检异常通常继承？","o":["RuntimeException","Exception","IOException","Error"],"a":0,"e":"RuntimeException 及其子类无需强制捕获。"},
{"id":"java-2-043","c":"java","l":2,"q":"OutOfMemoryError 属于？","o":["受检异常","IOException","Error","RuntimeException"],"a":2,"e":"Error 表示严重问题，一般不应捕获处理。"},
{"id":"java-2-044","c":"java","l":2,"q":"finally 中有 return 时，try 中的返回值会？","o":["被 finally 的 return 覆盖","抛出异常","编译错误","优先返回 try 的值"],"a":0,"e":"finally 的 return 会覆盖 try 的返回值并吞掉异常，应避免。"},
{"id":"java-2-045","c":"java","l":2,"q":"异常链（cause）的作用是？","o":["加快异常处理","保留原始异常信息","自动重试","忽略异常"],"a":1,"e":"通过 new XxxException(msg, cause) 保留根因便于排查。"},
{"id":"java-2-046","c":"java","l":2,"q":"Java 7 的多重捕获写法是？","o":["catch (IOException && SQLException e)","catch all","catch (IOException, SQLException e)","catch (IOException | SQLException e)"],"a":3,"e":"一个 catch 可用竖线分隔多个异常类型。"},
{"id":"java-2-047","c":"java","l":2,"q":"重写方法抛出的受检异常应满足？","o":["不能比父类方法声明的更宽泛","必须比父类更多","没有限制","必须完全相同"],"a":0,"e":"子类重写方法只能抛出父类方法声明异常的子集或子类。"},
{"id":"java-2-048","c":"java","l":2,"q":"volatile 关键字能保证？","o":["互斥访问","线程安全的 i++","可见性和禁止指令重排序","原子性"],"a":2,"e":"volatile 不保证复合操作如 i++ 的原子性。"},
{"id":"java-2-049","c":"java","l":2,"q":"sleep() 与 wait() 的区别，正确的是？","o":["两者都必须在 synchronized 中调用","sleep() 会释放锁","wait() 会释放对象锁","wait() 是 Thread 的方法"],"a":2,"e":"wait() 是 Object 方法，需持锁调用并会释放锁。"},
{"id":"java-2-050","c":"java","l":2,"q":"synchronized 修饰实例方法时，锁住的是？","o":["方法本身","当前实例 this","类的 Class 对象","所有实例"],"a":1,"e":"静态同步方法锁的是 Class 对象。"},
{"id":"java-2-051","c":"java","l":2,"q":"synchronized 修饰静态方法时锁住的是？","o":["this","没有锁","类的 Class 对象","方法区"],"a":2,"e":"静态方法属于类，锁对象是 XXX.class。"},
{"id":"java-2-052","c":"java","l":2,"q":"可以实现线程安全计数自增的类是？","o":["Integer","int[]","AtomicInteger","StringBuilder"],"a":2,"e":"AtomicInteger 基于 CAS 提供原子操作。"},
{"id":"java-2-053","c":"java","l":2,"q":"调用 notify() 前，线程必须？","o":["持有该对象的监视器锁","已调用 join()","是守护线程","处于睡眠状态"],"a":0,"e":"未持锁调用会抛出 IllegalMonitorStateException。"},
{"id":"java-2-054","c":"java","l":2,"q":"t.join() 的作用是？","o":["启动 t","当前线程等待 t 执行结束","t 等待当前线程","合并两个线程"],"a":1,"e":"join 让调用线程阻塞，直到目标线程终止。"},
{"id":"java-2-055","c":"java","l":2,"q":"线程的 interrupt() 方法的作用是？","o":["立即强制终止线程","设置中断标志，阻塞中的线程会抛出 InterruptedException","重启线程","暂停线程"],"a":1,"e":"中断是协作机制，线程需自行检查并响应。"},
{"id":"java-2-056","c":"java","l":2,"q":"守护线程（daemon）的特点是？","o":["不能被中断","必须手动结束 JVM","优先级最高","所有非守护线程结束后 JVM 会退出，不等待守护线程"],"a":3,"e":"GC 线程是典型的守护线程。"},
{"id":"java-2-057","c":"java","l":2,"q":"同一个 Thread 对象调用两次 start() 会？","o":["第二次被忽略","抛出 IllegalThreadStateException","重新执行","启动两个线程"],"a":1,"e":"线程只能启动一次。"},
{"id":"java-2-058","c":"java","l":2,"q":"Runnable 与 Callable 的区别是？","o":["两者相同","Callable 不能用于线程池","Runnable 可以返回结果","Callable 可以返回结果并抛出受检异常"],"a":3,"e":"Callable.call() 有返回值，可通过 Future 获取。"},
{"id":"java-2-059","c":"java","l":2,"q":"Future.get() 的行为是？","o":["立即返回 null","取消任务","启动任务","阻塞直到任务完成并返回结果"],"a":3,"e":"get() 会阻塞，也可传入超时时间。"},
{"id":"java-2-060","c":"java","l":2,"q":"创建线程池推荐的方式是？","o":["随意 new Thread","Executors.newCachedThreadPool 永远最优","直接使用 ThreadPoolExecutor 明确参数","使用 Timer"],"a":2,"e":"手动配置可避免无界队列或无限线程导致 OOM。"},
{"id":"java-2-061","c":"java","l":2,"q":"Executors.newFixedThreadPool 的潜在风险是？","o":["使用无界队列，任务堆积可能 OOM","不能执行任务","线程数无限","不支持 Callable"],"a":0,"e":"它使用 LinkedBlockingQueue（默认无界）。"},
{"id":"java-2-062","c":"java","l":2,"q":"线程的状态中，调用 wait() 无超时后处于？","o":["WAITING","TERMINATED","RUNNABLE","BLOCKED"],"a":0,"e":"无超时 wait/join 进入 WAITING；等待 synchronized 锁为 BLOCKED。"},
{"id":"java-2-063","c":"java","l":2,"q":"等待进入 synchronized 块的线程处于什么状态？","o":["BLOCKED","NEW","TIMED_WAITING","WAITING"],"a":0,"e":"竞争监视器锁失败的线程处于 BLOCKED。"},
{"id":"java-2-064","c":"java","l":2,"q":"死锁产生的必要条件不包括？","o":["线程优先级不同","持有并等待","互斥","循环等待"],"a":0,"e":"死锁四条件：互斥、持有并等待、不可剥夺、循环等待。"},
{"id":"java-2-065","c":"java","l":2,"q":"避免死锁的常用方法是？","o":["所有线程按固定顺序获取锁","增加线程数","提高优先级","使用 volatile"],"a":0,"e":"统一加锁顺序可破坏循环等待条件。"},
{"id":"java-2-066","c":"java","l":2,"q":"ReentrantLock 相比 synchronized 额外支持？","o":["自动释放锁","可中断、可超时获取锁和公平锁","只能用于静态方法","不需要解锁"],"a":1,"e":"ReentrantLock 需在 finally 中 unlock。"},
{"id":"java-2-067","c":"java","l":2,"q":"使用 ReentrantLock 时 unlock() 应放在？","o":["try 块开头","catch 块中","不需要调用","finally 块中"],"a":3,"e":"放在 finally 中确保异常时也能释放锁。"},
{"id":"java-2-068","c":"java","l":2,"q":"CountDownLatch 的典型用途是？","o":["限制并发数","一个或多个线程等待其他线程完成一组操作","交换数据","定时执行"],"a":1,"e":"计数减到 0 时等待线程被唤醒，不可重置。"},
{"id":"java-2-069","c":"java","l":2,"q":"Semaphore 的典型用途是？","o":["等待线程结束","保证可见性","限制同时访问资源的线程数","线程间交换数据"],"a":2,"e":"Semaphore 管理许可证数量。"},
{"id":"java-2-070","c":"java","l":2,"q":"ThreadLocal 的作用是？","o":["实现线程池","让变量在线程间共享","加锁","为每个线程提供独立的变量副本"],"a":3,"e":"每个线程通过 ThreadLocal 访问自己的值。"},
{"id":"java-2-071","c":"java","l":2,"q":"在线程池中使用 ThreadLocal 后应注意？","o":["无需处理","使用完调用 remove()，避免内存泄漏和数据串用","设为 static final 即可自动清理","必须用 volatile 修饰"],"a":1,"e":"线程被复用，残留值会泄漏或被下一个任务读到。"},
{"id":"java-2-072","c":"java","l":2,"q":"JVM 中线程私有的内存区域是？","o":["方法区","堆","字符串常量池","虚拟机栈"],"a":3,"e":"虚拟机栈、本地方法栈和程序计数器是线程私有的。"},
{"id":"java-2-073","c":"java","l":2,"q":"无限递归通常导致？","o":["StackOverflowError","NullPointerException","OutOfMemoryError: Java heap space","ClassNotFoundException"],"a":0,"e":"每次调用压入栈帧，栈深度超限即抛出 StackOverflowError。"},
{"id":"java-2-074","c":"java","l":2,"q":"Java 8 中 HotSpot 用什么替代了永久代？","o":["老年代","元空间 Metaspace","新生代","直接缓冲区"],"a":1,"e":"类元数据改存于本地内存的元空间。"},
{"id":"java-2-075","c":"java","l":2,"q":"类加载的双亲委派模型中，加载请求首先交给？","o":["随机加载器","当前加载器自己","父类加载器","最后加载的加载器"],"a":2,"e":"父加载器无法加载时才由自己加载。"},
{"id":"java-2-076","c":"java","l":2,"q":"HotSpot 判断对象是否可回收的主要算法是？","o":["可达性分析","引用计数法","标记计数法","随机采样"],"a":0,"e":"从 GC Roots 出发不可达的对象可被回收。"},
{"id":"java-2-077","c":"java","l":2,"q":"以下哪个可以作为 GC Roots？","o":["虚拟机栈中局部变量引用的对象","所有 String","堆中任意对象","已被回收的对象"],"a":0,"e":"栈中引用、静态变量引用、JNI 引用等都是 GC Roots。"},
{"id":"java-2-078","c":"java","l":2,"q":"-Xmx 参数用于设置？","o":["堆的最大大小","线程数","栈大小","元空间大小"],"a":0,"e":"-Xms 为初始堆大小，-Xmx 为最大堆大小。"},
{"id":"java-2-079","c":"java","l":2,"q":"-Xss 参数用于设置？","o":["每个线程的栈大小","堆大小","新生代大小","GC 线程数"],"a":0,"e":"-Xss 控制线程栈深度上限。"},
{"id":"java-2-080","c":"java","l":2,"q":"新创建的普通对象一般首先分配在？","o":["老年代","新生代 Eden 区","元空间","栈上永久存放"],"a":1,"e":"多数对象在 Eden 分配，存活多次 GC 后晋升老年代。"},
{"id":"java-2-081","c":"java","l":2,"q":"新生代的 Minor GC 主要采用的算法是？","o":["复制算法","引用计数","标记-清除","标记-整理"],"a":0,"e":"新生代对象存活率低，复制算法效率高。"},
{"id":"java-2-082","c":"java","l":2,"q":"System.gc() 的作用是？","o":["立即强制回收所有对象","建议 JVM 进行 GC，不保证立即执行","关闭 JVM","释放栈内存"],"a":1,"e":"它只是一个建议。"},
{"id":"java-2-083","c":"java","l":2,"q":"String s = new String(\"abc\"); 最多会创建几个对象？","o":["0 个","2 个","3 个","1 个"],"a":1,"e":"常量池中 \"abc\"（若不存在）加堆上的新 String 对象。"},
{"id":"java-2-084","c":"java","l":2,"q":"String.intern() 的作用是？","o":["复制字符串","删除字符串","返回常量池中的等值字符串引用","转为小写"],"a":2,"e":"若池中不存在则加入，并返回池中的引用。"},
{"id":"java-2-085","c":"java","l":2,"q":"String s1 = \"ab\"; String s2 = \"a\" + \"b\"; s1 == s2 的结果是？","o":["true","编译错误","false","不确定"],"a":0,"e":"常量表达式在编译期折叠为 \"ab\"，指向同一常量。"},
{"id":"java-2-086","c":"java","l":2,"q":"序列化时不想序列化某个字段应使用？","o":["volatile","private","transient","static final"],"a":2,"e":"transient 字段不参与默认序列化。"},
{"id":"java-2-087","c":"java","l":2,"q":"serialVersionUID 的作用是？","o":["校验序列化与反序列化的类版本是否兼容","加密数据","唯一标识对象","提升序列化速度"],"a":0,"e":"版本不一致时反序列化抛出 InvalidClassException。"},
{"id":"java-2-088","c":"java","l":2,"q":"反射中获取类的 Class 对象，以下哪个不可行？","o":["obj.getClass()","Y.class","Class.forName(\"x.Y\")","new Class()"],"a":3,"e":"Class 没有公共构造方法。"},
{"id":"java-2-089","c":"java","l":2,"q":"enum 类型的特点是？","o":["不能有方法","可以被继承","可以 new 实例","实例固定且隐式继承 java.lang.Enum"],"a":3,"e":"枚举构造器为私有，不能继承其他类。"},
{"id":"java-2-090","c":"java","l":2,"q":"枚举实现单例的优点是？","o":["天然防止反射和反序列化破坏单例","性能最差","可以懒加载任意参数","需要加锁"],"a":0,"e":"JVM 保证枚举实例唯一。"},
{"id":"java-2-091","c":"java","l":2,"q":"内部类中的静态嵌套类（static nested class）能直接访问外部类的？","o":["实例成员","this","静态成员","所有局部变量"],"a":2,"e":"静态嵌套类不持有外部类实例引用。"},
{"id":"java-2-092","c":"java","l":2,"q":"非静态内部类的潜在风险是？","o":["隐式持有外部类引用，可能导致内存泄漏","不能访问外部类","不能实例化","不能有方法"],"a":0,"e":"长生命周期的内部类对象会阻止外部对象回收。"},
{"id":"java-2-093","c":"java","l":2,"q":"接口中的 default 方法发生冲突（两个接口同名默认方法）时？","o":["实现类必须重写该方法","使用随机一个","编译器自动选择第一个","运行时报错"],"a":0,"e":"可在重写中用 A.super.method() 指定调用。"},
{"id":"java-2-094","c":"java","l":2,"q":"Java 8 起接口可包含哪种带方法体的方法？","o":["protected 方法","default 方法和 static 方法","synchronized 方法","final 方法"],"a":1,"e":"Java 9 起还支持 private 方法。"},
{"id":"java-2-095","c":"java","l":2,"q":"BufferedReader 的 readLine() 读到文件末尾时返回？","o":["空字符串","null","抛出 EOFException","-1"],"a":1,"e":"readLine 在流结束时返回 null。"},
{"id":"java-2-096","c":"java","l":2,"q":"字节流与字符流的基类分别是？","o":["File 与 Path","Scanner 与 Printer","InputStream/OutputStream 与 Reader/Writer","Reader 与 InputStream"],"a":2,"e":"字符流处理文本并涉及编码转换。"},
{"id":"java-2-097","c":"java","l":2,"q":"equals 相等的两个对象，hashCode 必须？","o":["为 0","可以任意","相等","不相等"],"a":2,"e":"这是 hashCode 通用约定；反之 hashCode 相等不要求 equals 相等。"},
{"id":"java-2-098","c":"java","l":2,"q":"BigDecimal 比较数值大小应使用？","o":["hashCode()","==","compareTo()","equals()"],"a":2,"e":"equals 还比较精度，new BigDecimal(\"1.0\") 与 \"1.00\" 不 equals。"},
{"id":"java-2-099","c":"java","l":2,"q":"0.1 + 0.2 == 0.3 在 Java 中的结果是？","o":["编译错误","true","抛出异常","false"],"a":3,"e":"二进制浮点无法精确表示 0.1，金额计算应使用 BigDecimal。"},
{"id":"java-2-100","c":"java","l":2,"q":"创建 BigDecimal 推荐的方式是？","o":["new BigDecimal(\"0.1\") 或 BigDecimal.valueOf(0.1)","(BigDecimal) 0.1","new BigDecimal(0.1)","BigDecimal.parse(0.1)"],"a":0,"e":"new BigDecimal(0.1) 会保留 double 的精度误差。"},
{"id":"java-3-001","c":"java","l":3,"q":"CAS（Compare-And-Swap）操作在 Java 中的底层主要依赖？","o":["GC 屏障","操作系统互斥锁","synchronized","CPU 的原子指令（如 x86 的 cmpxchg）"],"a":3,"e":"Unsafe/VarHandle 的 CAS 最终映射为处理器原子指令。"},
{"id":"java-3-002","c":"java","l":3,"q":"CAS 的 ABA 问题可以用哪个类解决？","o":["AtomicStampedReference","AtomicBoolean","LongAdder","AtomicInteger"],"a":0,"e":"带版本号（stamp）的引用可识别值被改回的情况。"},
{"id":"java-3-003","c":"java","l":3,"q":"高并发计数场景下 LongAdder 比 AtomicLong 更快的原因是？","o":["将热点分散到多个 Cell，降低 CAS 竞争","不保证最终结果","使用 volatile 数组排序","使用了 synchronized"],"a":0,"e":"sum() 时再汇总 base 和各 Cell 的值。"},
{"id":"java-3-004","c":"java","l":3,"q":"AQS（AbstractQueuedSynchronizer）用什么表示同步状态？","o":["一个 volatile int state","一个对象锁","ThreadLocal","一个 boolean 标志"],"a":0,"e":"子类通过 CAS 修改 state 实现各种同步器。"},
{"id":"java-3-005","c":"java","l":3,"q":"AQS 中等待获取资源的线程被组织为？","o":["CLH 变体的双向 FIFO 队列","红黑树","哈希表","栈"],"a":0,"e":"获取失败的线程封装成节点入队并被 park。"},
{"id":"java-3-006","c":"java","l":3,"q":"以下哪个不是基于 AQS 实现的？","o":["CountDownLatch","ReentrantLock","Semaphore","synchronized"],"a":3,"e":"synchronized 由 JVM 的对象监视器（monitor）实现。"},
{"id":"java-3-007","c":"java","l":3,"q":"ReentrantLock 默认是？","o":["公平锁","自旋锁","读写锁","非公平锁"],"a":3,"e":"new ReentrantLock(true) 才是公平锁；非公平吞吐量通常更高。"},
{"id":"java-3-008","c":"java","l":3,"q":"LockSupport.park() 的作用是？","o":["释放所有锁","阻塞当前线程直到 unpark、中断或虚假唤醒","终止线程","让出 CPU 一个时间片"],"a":1,"e":"unpark 可先于 park 调用，许可最多一个。"},
{"id":"java-3-009","c":"java","l":3,"q":"ReentrantReadWriteLock 支持的锁降级是指？","o":["写锁变为公平锁","释放所有锁","持有写锁时获取读锁，再释放写锁","持有读锁时获取写锁"],"a":2,"e":"读锁升级为写锁不被支持，会导致死锁。"},
{"id":"java-3-010","c":"java","l":3,"q":"StampedLock 的乐观读的特点是？","o":["阻塞所有写线程","不加锁，读后用 validate 校验期间是否有写","基于 synchronized","可重入"],"a":1,"e":"校验失败时再升级为悲观读锁；StampedLock 不可重入。"},
{"id":"java-3-011","c":"java","l":3,"q":"Condition 相比 Object.wait/notify 的优势是？","o":["不会虚假唤醒","一个锁可以有多个等待队列","性能一定更差","不需要持有锁"],"a":1,"e":"如生产者消费者可分别使用 notFull、notEmpty 条件。"},
{"id":"java-3-012","c":"java","l":3,"q":"wait() 应放在 while 循环中检查条件，主要原因是？","o":["提升性能","防止虚假唤醒和条件已被其他线程改变","避免死锁","语法要求"],"a":1,"e":"被唤醒后条件不一定成立，需要重新检查。"},
{"id":"java-3-013","c":"java","l":3,"q":"HotSpot 中 synchronized 的锁信息主要记录在？","o":["线程栈","方法区","对象头的 Mark Word","Class 文件"],"a":2,"e":"Mark Word 存储锁标志、哈希码、GC 年龄等。"},
{"id":"java-3-014","c":"java","l":3,"q":"JDK 15 起偏向锁的状态是？","o":["默认启用","成为唯一锁形态","默认禁用并被废弃","改为公平锁"],"a":2,"e":"JEP 374 默认禁用并废弃偏向锁，后续版本已移除。"},
{"id":"java-3-015","c":"java","l":3,"q":"synchronized 编译为字节码时，同步代码块使用？","o":["lock 和 unlock 指令","monitorenter 和 monitorexit 指令","invokedynamic","ACC_SYNCHRONIZED 仅此一种"],"a":1,"e":"同步方法则通过方法标志 ACC_SYNCHRONIZED 实现。"},
{"id":"java-3-016","c":"java","l":3,"q":"锁消除（lock elimination）依赖的 JIT 技术是？","o":["分代收集","字节码校验","类加载","逃逸分析"],"a":3,"e":"对象不逃逸出线程时，对其加锁可被消除。"},
{"id":"java-3-017","c":"java","l":3,"q":"Java 内存模型（JMM）中 happens-before 规则不包括？","o":["监视器锁规则","volatile 变量规则","程序顺序规则","线程优先级高的操作先发生"],"a":3,"e":"还有线程 start/join 规则和传递性等。"},
{"id":"java-3-018","c":"java","l":3,"q":"对 volatile 变量的写 happens-before 于？","o":["其他变量的写","线程结束","之前所有操作","之后对同一变量的读"],"a":3,"e":"这保证写线程之前的修改对读线程可见。"},
{"id":"java-3-019","c":"java","l":3,"q":"双重检查锁（DCL）单例中，实例字段必须用 volatile，原因是？","o":["防止反射","保证原子自增","提高性能","防止对象初始化与引用赋值重排序，导致读到未初始化对象"],"a":3,"e":"new 可能被重排为先赋值引用后初始化。"},
{"id":"java-3-020","c":"java","l":3,"q":"final 字段在 JMM 中的特殊保证是？","o":["构造正确完成后，其他线程可看到 final 字段的初始化值","final 字段存储在栈上","final 字段不可读","final 字段线程私有"],"a":0,"e":"前提是构造期间 this 没有逸出。"},
{"id":"java-3-021","c":"java","l":3,"q":"Thread.start() 与 happens-before 的关系是？","o":["新线程的操作对主线程可见","start() 之前的操作对新线程可见","没有关系","只对 volatile 有效"],"a":1,"e":"线程启动规则是 happens-before 规则之一。"},
{"id":"java-3-022","c":"java","l":3,"q":"ThreadPoolExecutor 提交任务时，核心线程已满后会先？","o":["阻塞提交线程","放入工作队列","立即创建非核心线程","直接拒绝"],"a":1,"e":"队列满后才创建非核心线程，达到最大线程数后执行拒绝策略。"},
{"id":"java-3-023","c":"java","l":3,"q":"ThreadPoolExecutor 默认的拒绝策略是？","o":["CallerRunsPolicy","DiscardPolicy","AbortPolicy，抛出 RejectedExecutionException","DiscardOldestPolicy"],"a":2,"e":"CallerRunsPolicy 由提交线程执行任务，可起到减速作用。"},
{"id":"java-3-024","c":"java","l":3,"q":"线程池中的非核心线程在何时被回收？","o":["永不回收","GC 时","任务完成立即回收","空闲超过 keepAliveTime"],"a":3,"e":"allowCoreThreadTimeOut(true) 时核心线程也可超时回收。"},
{"id":"java-3-025","c":"java","l":3,"q":"execute() 提交的任务抛出未捕获异常时？","o":["异常被静默吞掉且线程保留","异常存入 Future","整个线程池关闭","工作线程终止并被替换，异常交给 UncaughtExceptionHandler"],"a":3,"e":"submit() 则把异常封装在 Future 中，get() 时抛出。"},
{"id":"java-3-026","c":"java","l":3,"q":"shutdown() 与 shutdownNow() 的区别是？","o":["shutdownNow 会中断正在执行的任务并返回未执行的任务","shutdown 立即终止所有任务","shutdownNow 等待所有任务完成","两者相同"],"a":0,"e":"shutdown 不再接受新任务，但会执行完已提交任务。"},
{"id":"java-3-027","c":"java","l":3,"q":"CPU 密集型任务的线程池大小一般建议设置为？","o":["1","CPU 核数的 10 倍","约等于 CPU 核数（N 或 N+1）","无上限"],"a":2,"e":"I/O 密集型任务可以设置更多线程。"},
{"id":"java-3-028","c":"java","l":3,"q":"ForkJoinPool 使用的任务调度算法是？","o":["优先级调度","工作窃取（work-stealing）","先来先服务全局队列","轮询"],"a":1,"e":"空闲线程从其他线程的双端队列尾部窃取任务。"},
{"id":"java-3-029","c":"java","l":3,"q":"parallelStream() 默认使用的线程池是？","o":["ForkJoinPool.commonPool()","FixedThreadPool(10)","新建的 CachedThreadPool","调用线程单独执行"],"a":0,"e":"在其中执行阻塞任务会影响全局其他并行流。"},
{"id":"java-3-030","c":"java","l":3,"q":"CompletableFuture.thenCompose 与 thenApply 的区别是？","o":["thenApply 是异步的","两者完全相同","thenCompose 用于连接返回 CompletableFuture 的函数，结果被扁平化","thenCompose 不能链式调用"],"a":2,"e":"类似 Stream 的 flatMap 与 map。"},
{"id":"java-3-031","c":"java","l":3,"q":"CompletableFuture.supplyAsync 未指定线程池时默认使用？","o":["Spring 线程池","ForkJoinPool.commonPool()","调用线程","新线程"],"a":1,"e":"当 commonPool 并行度不足（如单核）时会为每个任务新建线程。"},
{"id":"java-3-032","c":"java","l":3,"q":"CompletableFuture 的 allOf 返回？","o":["所有结果组成的 List","一个 int","第一个完成的结果","CompletableFuture<Void>，所有任务完成时完成"],"a":3,"e":"需要逐个 join() 获取各结果；anyOf 在任一完成时完成。"},
{"id":"java-3-033","c":"java","l":3,"q":"Java 21 中虚拟线程（Virtual Thread）的特点是？","o":["一定比平台线程计算更快","由 JVM 调度、挂载在少量平台线程上的轻量级线程","需要操作系统内核支持协程","不能使用 synchronized"],"a":1,"e":"适合大量阻塞 I/O 任务，CPU 密集任务不会更快。"},
{"id":"java-3-034","c":"java","l":3,"q":"虚拟线程被 pinned（钉住）在载体线程上的典型场景（Java 21）是？","o":["在 synchronized 块中阻塞","使用 ReentrantLock","调用 Thread.sleep()","读取 volatile 变量"],"a":0,"e":"Java 24（JEP 491）已基本解决 synchronized 导致的钉住问题。"},
{"id":"java-3-035","c":"java","l":3,"q":"BlockingQueue 中 put() 在队列满时会？","o":["覆盖队首","返回 false","抛出异常","阻塞直到有空间"],"a":3,"e":"offer() 返回 false，add() 抛出异常。"},
{"id":"java-3-036","c":"java","l":3,"q":"SynchronousQueue 的特点是？","o":["按优先级排序","延迟队列","无界队列","容量为 0，每个插入必须等待一个移除"],"a":3,"e":"newCachedThreadPool 使用 SynchronousQueue。"},
{"id":"java-3-037","c":"java","l":3,"q":"CopyOnWriteArrayList 适合的场景是？","o":["读多写少","需要强一致迭代","写多读少","大量随机删除"],"a":0,"e":"每次写入都会复制底层数组，迭代器基于快照。"},
{"id":"java-3-038","c":"java","l":3,"q":"Java 8 ConcurrentHashMap 的主要并发机制是？","o":["ReadWriteLock","Segment 分段锁","CAS + 对桶头节点 synchronized","全表 synchronized"],"a":2,"e":"Java 7 使用 Segment 分段锁，Java 8 改为更细粒度的桶级锁。"},
{"id":"java-3-039","c":"java","l":3,"q":"ConcurrentHashMap 是否允许 null 键或 null 值？","o":["都允许","只允许 null 值","都不允许","只允许 null 键"],"a":2,"e":"null 会造成 get 返回 null 时的二义性。"},
{"id":"java-3-040","c":"java","l":3,"q":"ConcurrentHashMap 的 size() 结果特点是？","o":["需要加全局锁","始终为 0","总是精确","并发修改时是估计值，不保证精确"],"a":3,"e":"它基于类似 LongAdder 的 baseCount 和 CounterCell 计数。"},
{"id":"java-3-041","c":"java","l":3,"q":"HashMap 在多线程下同时 put 的风险，Java 8 中主要是？","o":["不可能出错","数据丢失或覆盖等不一致","抛出编译错误","一定死锁"],"a":1,"e":"Java 7 头插法扩容可能形成环形链表，Java 8 改为尾插但仍不线程安全。"},
{"id":"java-3-042","c":"java","l":3,"q":"HashMap 计算哈希时 (h = key.hashCode()) ^ (h >>> 16) 的目的是？","o":["加密","防止 null","让高位参与运算，减少碰撞","提升序列化性能"],"a":2,"e":"容量较小时索引只用到低位，扰动函数混入高位信息。"},
{"id":"java-3-043","c":"java","l":3,"q":"可变对象作为 HashMap 键，存入后修改其参与 hashCode 的字段会？","o":["抛出异常","没有影响","自动重新哈希","可能再也无法通过 get 找到该条目"],"a":3,"e":"键应使用不可变对象，或保证哈希相关字段不变。"},
{"id":"java-3-044","c":"java","l":3,"q":"WeakHashMap 的键在何时可能被移除？","o":["插入 10 分钟后","永不移除","键对象只被弱引用可达并被 GC 回收后","容量满时"],"a":2,"e":"适合实现缓存，但值不应强引用键。"},
{"id":"java-3-045","c":"java","l":3,"q":"软引用（SoftReference）对象在何时被回收？","o":["下一次 GC 时一定回收","永不回收","线程结束时","内存不足、即将 OOM 之前"],"a":3,"e":"弱引用在下一次 GC 时即可被回收。"},
{"id":"java-3-046","c":"java","l":3,"q":"虚引用（PhantomReference）的主要用途是？","o":["防止回收","获取对象","配合 ReferenceQueue 跟踪对象被回收的时机","加速 GC"],"a":2,"e":"虚引用的 get() 总是返回 null。"},
{"id":"java-3-047","c":"java","l":3,"q":"G1 垃圾回收器将堆划分为？","o":["固定的新生代和老年代两块连续空间","多个大小相等的 Region","多个线程栈","一个整体"],"a":1,"e":"Region 可动态扮演 Eden、Survivor、Old 或 Humongous。"},
{"id":"java-3-048","c":"java","l":3,"q":"G1 中的 Humongous Region 用于存放？","o":["元数据","字符串常量","线程栈","大小超过 Region 一半的大对象"],"a":3,"e":"大对象直接分配在一个或多个连续 Humongous Region 中。"},
{"id":"java-3-049","c":"java","l":3,"q":"从 JDK 9 开始，HotSpot 的默认垃圾回收器是？","o":["CMS","G1","Serial GC","Parallel GC"],"a":1,"e":"JDK 8 服务器模式默认是 Parallel GC。"},
{"id":"java-3-050","c":"java","l":3,"q":"ZGC 的主要设计目标是？","o":["单线程回收","只用于小堆","最大化吞吐量而不关心停顿","停顿时间极短（亚毫秒级）且与堆大小基本无关"],"a":3,"e":"ZGC 使用染色指针和读屏障实现并发整理。"},
{"id":"java-3-051","c":"java","l":3,"q":"GC 中的 Stop-The-World 指？","o":["停止 JVM","停止 GC 线程","只暂停一个线程","GC 时暂停所有应用线程"],"a":3,"e":"并发回收器的目标是缩短 STW 时间。"},
{"id":"java-3-052","c":"java","l":3,"q":"安全点（Safepoint）的作用是？","o":["线程只能在特定位置暂停，以便 GC 等操作安全进行","内存屏障","加锁位置","类加载位置"],"a":0,"e":"方法调用、循环回边等位置通常设置安全点。"},
{"id":"java-3-053","c":"java","l":3,"q":"卡表（Card Table）在分代 GC 中用于？","o":["记录老年代指向新生代的引用，避免 Minor GC 扫描整个老年代","记录线程状态","记录类信息","存储对象"],"a":0,"e":"它是记忆集（Remembered Set）的一种实现。"},
{"id":"java-3-054","c":"java","l":3,"q":"三色标记中，并发标记期间可能出现对象漏标，需要什么来解决？","o":["关闭 JIT","更大的堆","更多 GC 线程","写屏障（如增量更新或 SATB）"],"a":3,"e":"CMS 使用增量更新，G1 使用 SATB（原始快照）。"},
{"id":"java-3-055","c":"java","l":3,"q":"TLAB（Thread Local Allocation Buffer）的作用是？","o":["存放线程栈","存放锁","存放 ThreadLocal 变量","每个线程在 Eden 中预先分配私有缓冲区，减少分配时的同步"],"a":3,"e":"TLAB 让对象分配通常只需指针碰撞。"},
{"id":"java-3-056","c":"java","l":3,"q":"对象从新生代晋升老年代的默认年龄阈值（-XX:MaxTenuringThreshold）通常是？","o":["15","8","100","1"],"a":0,"e":"对象头中年龄占 4 位，最大为 15；动态年龄判断可能更早晋升。"},
{"id":"java-3-057","c":"java","l":3,"q":"Survivor 区设置两个（From/To）的主要原因是？","o":["配合复制算法，每次 GC 将存活对象复制到空的 Survivor","存放元数据","存放大对象","增加容量"],"a":0,"e":"复制后 From 被清空，两者角色互换。"},
{"id":"java-3-058","c":"java","l":3,"q":"大对象直接进入老年代可通过哪个参数控制（Serial/ParNew 下）？","o":["-XX:PretenureSizeThreshold","-XX:NewRatio","-XX:MetaspaceSize","-Xss"],"a":0,"e":"避免大对象在 Survivor 间反复复制。"},
{"id":"java-3-059","c":"java","l":3,"q":"逃逸分析可能带来的优化不包括？","o":["增大堆空间","锁消除","标量替换","栈上分配（概念上）"],"a":0,"e":"HotSpot 主要实现了标量替换和锁消除。"},
{"id":"java-3-060","c":"java","l":3,"q":"“OutOfMemoryError: Metaspace” 通常由什么引起？","o":["加载过多的类（如动态生成大量代理类）","堆中对象太多","线程太多","递归太深"],"a":0,"e":"可通过 -XX:MaxMetaspaceSize 限制并排查类加载泄漏。"},
{"id":"java-3-061","c":"java","l":3,"q":"“OutOfMemoryError: unable to create native thread” 通常与什么有关？","o":["堆太小","元空间不足","线程数过多或系统资源限制","字符串过多"],"a":2,"e":"每个线程需要栈内存和操作系统线程资源。"},
{"id":"java-3-062","c":"java","l":3,"q":"生成堆转储（heap dump）的常用命令是？","o":["jstack <pid>","javap","jmap -dump:format=b,file=heap.hprof <pid>","jps -v"],"a":2,"e":"也可用 jcmd <pid> GC.heap_dump，或配置 -XX:+HeapDumpOnOutOfMemoryError。"},
{"id":"java-3-063","c":"java","l":3,"q":"排查线程死锁最直接的工具是？","o":["jar","javac","jmap","jstack"],"a":3,"e":"jstack 可打印线程栈，并报告检测到的 Java 级死锁。"},
{"id":"java-3-064","c":"java","l":3,"q":"类加载过程的顺序是？","o":["解析 → 加载 → 准备","加载 → 链接（验证、准备、解析）→ 初始化","初始化 → 加载 → 验证","验证 → 加载 → 初始化"],"a":1,"e":"准备阶段为静态变量分配内存并设零值。"},
{"id":"java-3-065","c":"java","l":3,"q":"static int a = 10; 在类加载的准备阶段 a 的值是？","o":["未分配","null","10","0"],"a":3,"e":"赋值 10 发生在初始化阶段的 <clinit>；static final 编译期常量除外。"},
{"id":"java-3-066","c":"java","l":3,"q":"以下哪种情况不会触发类的初始化？","o":["new 该类实例","反射 Class.forName(\"X\")","调用该类的静态方法","通过子类引用父类的静态字段（子类不会初始化）"],"a":3,"e":"被动引用只初始化定义该字段的父类。"},
{"id":"java-3-067","c":"java","l":3,"q":"打破双亲委派模型的典型例子是？","o":["普通 new 对象","使用 static 方法","加载 java.lang.String","JDBC 使用线程上下文类加载器加载驱动（SPI）"],"a":3,"e":"SPI 接口由启动类加载器加载，实现需由应用类加载器加载。"},
{"id":"java-3-068","c":"java","l":3,"q":"两个类“相同”的判定条件是？","o":["包名相同","字节码相同即可","全限定名相同即可","类的全限定名相同且由同一个类加载器加载"],"a":3,"e":"不同类加载器加载的同名类互相转换会抛出 ClassCastException。"},
{"id":"java-3-069","c":"java","l":3,"q":"HotSpot JIT 编译器 C1 与 C2 的区别是？","o":["C1 只用于 GC","两者相同","C2 是解释器","C1 编译快、优化少，C2 编译慢、优化激进"],"a":3,"e":"分层编译先用 C1，热点代码再交给 C2。"},
{"id":"java-3-070","c":"java","l":3,"q":"JIT 中方法内联的主要收益是？","o":["消除调用开销并为其他优化创造条件","增加安全性","减少 GC","减少类加载"],"a":0,"e":"内联是许多后续优化的基础。"},
{"id":"java-3-071","c":"java","l":3,"q":"invokedynamic 指令在 Java 中被用于实现？","o":["普通实例方法调用","Lambda 表达式和字符串拼接优化","异常处理","静态方法调用"],"a":1,"e":"Java 9 起字符串拼接也通过 StringConcatFactory 使用 invokedynamic。"},
{"id":"java-3-072","c":"java","l":3,"q":"以下哪种方法调用使用 invokevirtual 指令？","o":["构造方法","私有方法（Java 11 前）","静态方法","普通的公共实例方法"],"a":3,"e":"静态方法用 invokestatic，构造方法用 invokespecial。"},
{"id":"java-3-073","c":"java","l":3,"q":"泛型方法 <T extends Comparable<? super T>> T max(List<? extends T> list) 中 ? super T 的作用是？","o":["允许 T 使用父类实现的 compareTo","限制 T 必须是 final","使 T 可以为基本类型","没有作用"],"a":0,"e":"例如 java.sql.Date 继承 java.util.Date 实现的 Comparable<java.util.Date>。"},
{"id":"java-3-074","c":"java","l":3,"q":"PECS 原则指的是？","o":["Public Extends, Class Super","Producer Extends, Consumer Super","Private Encapsulation","Parallel Execution"],"a":1,"e":"只读取用 extends，只写入用 super。"},
{"id":"java-3-075","c":"java","l":3,"q":"List<? extends Number> list 能调用 list.add(1) 吗？","o":["只能添加 Integer","能","不能（只能添加 null）","只能添加 Number"],"a":2,"e":"编译器无法确定具体元素类型，因此禁止添加。"},
{"id":"java-3-076","c":"java","l":3,"q":"由于类型擦除，以下哪个重载会编译失败？","o":["void f(String a) 与 void f(Object a)","void f(List<String> a) 与 void f(List<Integer> a)","void f(int a) 与 void f(long a)","void f() 与 void f(int a)"],"a":1,"e":"擦除后两者签名都是 f(List)，发生冲突。"},
{"id":"java-3-077","c":"java","l":3,"q":"可以通过反射获取的泛型信息是？","o":["全部都不可以","局部变量的实际泛型类型","new ArrayList<String>() 实例运行时的元素类型","字段、方法签名和父类声明中的泛型参数"],"a":3,"e":"Signature 属性保留了声明处的泛型信息。"},
{"id":"java-3-078","c":"java","l":3,"q":"桥接方法（bridge method）产生的原因是？","o":["提升性能","实现序列化","泛型擦除后保证子类重写方法的多态性","方便反射"],"a":2,"e":"编译器生成合成方法，将擦除后的签名转发到实际重写方法。"},
{"id":"java-3-079","c":"java","l":3,"q":"不能创建泛型数组 new List<String>[10] 的主要原因是？","o":["JVM 不支持数组","数组不能存放对象","语法太复杂","数组运行时需要检查元素类型，而泛型类型已被擦除"],"a":3,"e":"这会破坏数组存储检查的类型安全。"},
{"id":"java-3-080","c":"java","l":3,"q":"record（Java 16）的特点是？","o":["不可变数据载体，自动生成构造器、访问器、equals、hashCode 和 toString","可以继承其他类","字段可以被重新赋值","不能有方法"],"a":0,"e":"record 隐式为 final，并隐式继承 java.lang.Record。"},
{"id":"java-3-081","c":"java","l":3,"q":"sealed 类（Java 17）的作用是？","o":["禁止序列化","限制哪些类可以继承或实现它","让类不可实例化","让类线程安全"],"a":1,"e":"子类必须声明为 final、sealed 或 non-sealed。"},
{"id":"java-3-082","c":"java","l":3,"q":"Java 21 中 switch 的模式匹配对 sealed 接口的好处是？","o":["编译器可以检查分支穷尽，可省略 default","运行更快","允许 goto","不需要 case"],"a":0,"e":"新增子类型未处理时会产生编译错误。"},
{"id":"java-3-083","c":"java","l":3,"q":"建造者模式（Builder）最适合解决？","o":["构造参数多且很多为可选的问题","对象需要全局唯一","需要监听事件","算法需要切换"],"a":0,"e":"Builder 避免冗长的重叠构造器，提高可读性。"},
{"id":"java-3-084","c":"java","l":3,"q":"静态内部类（Holder）方式实现单例的线程安全性来源于？","o":["类初始化由 JVM 保证只执行一次且线程安全","synchronized 方法","CAS","volatile"],"a":0,"e":"Holder 类在首次使用时加载，实现懒加载且无需加锁。"},
{"id":"java-3-085","c":"java","l":3,"q":"策略模式的核心思想是？","o":["拦截方法调用","保证类只有一个实例","把对象组织成树","把可替换的算法封装成独立对象，在运行时切换"],"a":3,"e":"常与 Lambda 结合，用函数式接口表示策略。"},
{"id":"java-3-086","c":"java","l":3,"q":"JDK 动态代理（java.lang.reflect.Proxy）的限制是？","o":["只能代理静态方法","不需要 InvocationHandler","只能代理 final 类","只能代理接口"],"a":3,"e":"代理类需继承无法代理的方法时，常用字节码生成库（如 ByteBuddy）。"},
{"id":"java-3-087","c":"java","l":3,"q":"装饰器模式在 JDK 中的典型应用是？","o":["Runtime.getRuntime()","java.io 的 BufferedInputStream 包装 InputStream","Thread","Collections.sort"],"a":1,"e":"装饰器在不修改原类的情况下动态增加功能。"},
{"id":"java-3-088","c":"java","l":3,"q":"观察者模式的核心是？","o":["延迟创建","对象复制","统一接口适配","主题状态变化时通知所有已注册的观察者"],"a":3,"e":"它实现了发布者与订阅者之间的解耦。"},
{"id":"java-3-089","c":"java","l":3,"q":"“组合优于继承”的主要理由是？","o":["Java 不支持继承","继承无法编译","降低耦合，避免继承破坏封装","组合运行更快"],"a":2,"e":"子类依赖父类实现细节，父类变化可能破坏子类。"},
{"id":"java-3-090","c":"java","l":3,"q":"里氏替换原则（LSP）是指？","o":["父类可以替换子类","类只做一件事","依赖抽象而非具体","子类对象必须能替换父类对象且不破坏程序正确性"],"a":3,"e":"正方形继承长方形是常见的违反 LSP 示例。"},
{"id":"java-3-091","c":"java","l":3,"q":"依赖倒置原则（DIP）是指？","o":["低层模块依赖高层实现","类之间不应有依赖","所有类都应为 final","高层模块和低层模块都依赖抽象"],"a":3,"e":"面向接口编程是 DIP 的体现。"},
{"id":"java-3-092","c":"java","l":3,"q":"不可变类的设计要点不包括？","o":["类声明为 final","所有字段为 private final","对可变字段做防御性拷贝","提供 setter 方法"],"a":3,"e":"不可变对象天然线程安全。"},
{"id":"java-3-093","c":"java","l":3,"q":"Object.clone() 默认实现的拷贝方式是？","o":["深拷贝","浅拷贝","序列化拷贝","不拷贝"],"a":1,"e":"引用类型字段只复制引用；类需实现 Cloneable，否则抛出 CloneNotSupportedException。"},
{"id":"java-3-094","c":"java","l":3,"q":"Java 9 模块系统（JPMS）中 module-info.java 的 exports 的作用是？","o":["声明依赖","开放反射","指定主类","声明哪些包对其他模块可见"],"a":3,"e":"requires 声明依赖，opens 开放深度反射访问。"},
{"id":"java-3-095","c":"java","l":3,"q":"Java 中 String 内部存储在 JDK 9 后改为？","o":["char[]","StringBuilder","byte[] 加编码标志（Compact Strings）","int[]"],"a":2,"e":"Latin-1 字符串每个字符只占 1 字节，节省内存。"},
{"id":"java-3-096","c":"java","l":3,"q":"JDK 7 起字符串常量池位于？","o":["元空间","永久代","栈中","堆中"],"a":3,"e":"JDK 7 将字符串常量池从永久代移到堆中。"},
{"id":"java-3-097","c":"java","l":3,"q":"-XX:+UseCompressedOops 的作用是？","o":["压缩 GC 日志","在 64 位 JVM 上用 32 位压缩对象指针节省内存","压缩字符串","压缩 class 文件"],"a":1,"e":"堆小于约 32GB 时默认启用。"},
{"id":"java-3-098","c":"java","l":3,"q":"volatile long 变量的读写在 JMM 中是否原子？","o":["否","只在 64 位机器上是","只读是原子的","是"],"a":3,"e":"JMM 规定非 volatile 的 long/double 读写允许拆分为两次 32 位操作。"},
{"id":"java-3-099","c":"java","l":3,"q":"i++ 不是原子操作的原因是？","o":["编译器会优化掉","只有 long 才不是原子的","Java 不支持整数加法","它包含读取、加一、写回三个步骤"],"a":3,"e":"多线程交错执行会导致更新丢失。"},
{"id":"java-3-100","c":"java","l":3,"q":"伪共享（false sharing）指的是？","o":["ThreadLocal 冲突","两个线程共享同一个变量","多个线程修改位于同一缓存行的不同变量，导致缓存行频繁失效","GC 误回收"],"a":2,"e":"可用 @Contended 或填充字段缓解。"},
{"id":"sql-1-001","c":"sql","l":1,"q":"SQL 是什么的缩写？","o":["Simple Query Language","Standard Question Language","System Query Logic","Structured Query Language"],"a":3,"e":"SQL 即结构化查询语言，用于管理关系型数据库。"},
{"id":"sql-1-002","c":"sql","l":1,"q":"从表中查询数据使用的关键字是？","o":["READ","FETCH","SELECT","GET"],"a":2,"e":"SELECT 用于从表中检索数据。"},
{"id":"sql-1-003","c":"sql","l":1,"q":"查询 users 表所有列的写法是？","o":["SELECT users.*all","SELECT * FROM users","SELECT ALL users","GET * FROM users"],"a":1,"e":"* 表示所有列；实际开发中建议只查询需要的列。"},
{"id":"sql-1-004","c":"sql","l":1,"q":"过滤行使用的子句是？","o":["WHERE","IF","FILTER","HAVING"],"a":0,"e":"WHERE 在分组前按条件过滤行。"},
{"id":"sql-1-005","c":"sql","l":1,"q":"查询 name 列不为空的记录，正确写法是？","o":["WHERE name <> NULL","WHERE NOT name = NULL","WHERE name != NULL","WHERE name IS NOT NULL"],"a":3,"e":"与 NULL 比较须用 IS (NOT) NULL，= 或 <> 的结果是 UNKNOWN。"},
{"id":"sql-1-006","c":"sql","l":1,"q":"LIKE 'a_%' 能匹配以下哪个值？","o":["空字符串","a","ab","ba"],"a":2,"e":"_ 匹配恰好一个字符，% 匹配零个或多个字符。"},
{"id":"sql-1-007","c":"sql","l":1,"q":"LIKE '%abc%' 的含义是？","o":["以 abc 结尾","以 abc 开头","包含 abc","等于 abc"],"a":2,"e":"% 两侧通配表示任意位置包含该子串。"},
{"id":"sql-1-008","c":"sql","l":1,"q":"BETWEEN 10 AND 20 包含的范围是？","o":["10 < x <= 20","10 < x < 20","10 <= x < 20","10 <= x <= 20"],"a":3,"e":"BETWEEN 是闭区间，包含两端的值。"},
{"id":"sql-1-009","c":"sql","l":1,"q":"去除查询结果中的重复行使用？","o":["DIFFERENT","GROUP","UNIQUE","DISTINCT"],"a":3,"e":"SELECT DISTINCT 去除完全相同的行。"},
{"id":"sql-1-010","c":"sql","l":1,"q":"ORDER BY 默认的排序方式是？","o":["随机","升序 ASC","插入顺序","降序 DESC"],"a":1,"e":"未指定时默认 ASC。"},
{"id":"sql-1-011","c":"sql","l":1,"q":"按 salary 降序排列的写法是？","o":["ORDER salary DESC","ORDER BY salary DOWN","SORT BY salary DESC","ORDER BY salary DESC"],"a":3,"e":"DESC 表示降序。"},
{"id":"sql-1-012","c":"sql","l":1,"q":"ORDER BY a, b DESC 的含义是？","o":["a、b 都降序","只按 b 降序","先按 a 升序，a 相同再按 b 降序","按 a+b 降序"],"a":2,"e":"每个排序列单独指定方向，默认 ASC。"},
{"id":"sql-1-013","c":"sql","l":1,"q":"MySQL 中限制返回前 10 行使用？","o":["TOP 10","ROWNUM <= 10","FIRST 10","LIMIT 10"],"a":3,"e":"TOP 是 SQL Server 语法，ROWNUM 是 Oracle 语法。"},
{"id":"sql-1-014","c":"sql","l":1,"q":"MySQL 中 LIMIT 10, 5 的含义是？","o":["返回第 5 到 10 行","跳过 5 行返回 10 行","返回 10 行","跳过前 10 行，返回 5 行"],"a":3,"e":"LIMIT offset, count，等价于 LIMIT 5 OFFSET 10。"},
{"id":"sql-1-015","c":"sql","l":1,"q":"IN (1, 2, 3) 等价于？","o":["= 1 AND = 2 AND = 3","> 1 AND < 3","BETWEEN 1 AND 3 用于任何类型","= 1 OR = 2 OR = 3"],"a":3,"e":"IN 判断值是否属于列表。"},
{"id":"sql-1-016","c":"sql","l":1,"q":"AND 与 OR 的优先级关系是？","o":["相同","OR 高于 AND","AND 高于 OR","取决于数据库"],"a":2,"e":"混合使用时建议加括号明确逻辑。"},
{"id":"sql-1-017","c":"sql","l":1,"q":"给列起别名使用的关键字是？","o":["ALIAS","AS","RENAME","NAME"],"a":1,"e":"AS 可以省略，如 SELECT price p。"},
{"id":"sql-1-018","c":"sql","l":1,"q":"NULL + 1 的结果是？","o":["报错","NULL","0","1"],"a":1,"e":"大多数涉及 NULL 的算术运算结果为 NULL。"},
{"id":"sql-1-019","c":"sql","l":1,"q":"MySQL 中将 NULL 替换为默认值可用？","o":["NVL2","IFNULL(col, 0) 或 COALESCE(col, 0)","ISNULL(col, 0)（MySQL 中）","ZERO(col)"],"a":1,"e":"COALESCE 是标准 SQL，返回第一个非 NULL 参数。"},
{"id":"sql-1-020","c":"sql","l":1,"q":"插入数据使用的语句是？","o":["INSERT INTO","INSERT TABLE","PUT INTO","ADD INTO"],"a":0,"e":"INSERT INTO t (cols) VALUES (...)。"},
{"id":"sql-1-021","c":"sql","l":1,"q":"修改已有数据使用的语句是？","o":["CHANGE","MODIFY","ALTER","UPDATE"],"a":3,"e":"UPDATE ... SET ... WHERE ...；ALTER 用于修改表结构。"},
{"id":"sql-1-022","c":"sql","l":1,"q":"UPDATE 语句漏写 WHERE 会怎样？","o":["只更新第一行","报错","不更新任何行","更新表中所有行"],"a":3,"e":"务必检查 WHERE，必要时先用 SELECT 确认范围。"},
{"id":"sql-1-023","c":"sql","l":1,"q":"删除表中满足条件的行使用？","o":["DROP ... WHERE","REMOVE FROM","TRUNCATE ... WHERE","DELETE FROM ... WHERE"],"a":3,"e":"DELETE 删除行；DROP 删除整张表。"},
{"id":"sql-1-024","c":"sql","l":1,"q":"DELETE、TRUNCATE、DROP 中，删除表结构的是？","o":["TRUNCATE","DELETE","三者都会","DROP"],"a":3,"e":"TRUNCATE 清空数据但保留结构。"},
{"id":"sql-1-025","c":"sql","l":1,"q":"MySQL InnoDB 中 TRUNCATE 与 DELETE 不带条件的区别，正确的是？","o":["TRUNCATE 会重置 AUTO_INCREMENT 计数","TRUNCATE 可以带 WHERE","DELETE 会重置自增值","两者都会触发 DELETE 触发器"],"a":0,"e":"TRUNCATE 是 DDL，会隐式提交，不能回滚，也不触发 DELETE 触发器。"},
{"id":"sql-1-026","c":"sql","l":1,"q":"创建表使用的语句是？","o":["MAKE TABLE","CREATE TABLE","ADD TABLE","NEW TABLE"],"a":1,"e":"CREATE TABLE 定义列名、类型和约束。"},
{"id":"sql-1-027","c":"sql","l":1,"q":"给已有表增加一列使用？","o":["ALTER TABLE t ADD COLUMN c INT","MODIFY t ADD c","INSERT COLUMN c","UPDATE TABLE t ADD c"],"a":0,"e":"ALTER TABLE 用于修改表结构。"},
{"id":"sql-1-028","c":"sql","l":1,"q":"主键（PRIMARY KEY）的特点是？","o":["可以为 NULL","一张表可以有多个主键","唯一且非空","可以重复"],"a":2,"e":"一张表只能有一个主键，但可以由多列组成。"},
{"id":"sql-1-029","c":"sql","l":1,"q":"UNIQUE 约束与主键的区别是？","o":["两者完全相同","UNIQUE 列允许 NULL，一张表可以有多个 UNIQUE","UNIQUE 不允许 NULL","UNIQUE 只能有一个"],"a":1,"e":"MySQL 中 UNIQUE 列可以有多个 NULL。"},
{"id":"sql-1-030","c":"sql","l":1,"q":"外键（FOREIGN KEY）的作用是？","o":["防止 NULL","保证引用完整性，引用另一张表的键","加快查询","自动生成编号"],"a":1,"e":"MySQL 中只有 InnoDB 等引擎支持外键约束。"},
{"id":"sql-1-031","c":"sql","l":1,"q":"NOT NULL 约束的作用是？","o":["禁止重复","创建索引","设置默认值","禁止该列为 NULL"],"a":3,"e":"插入或更新为 NULL 时报错（严格模式下）。"},
{"id":"sql-1-032","c":"sql","l":1,"q":"DEFAULT 约束的作用是？","o":["自动递增","插入时未提供值则使用默认值","校验范围","禁止修改"],"a":1,"e":"例如 created_at DATETIME DEFAULT CURRENT_TIMESTAMP。"},
{"id":"sql-1-033","c":"sql","l":1,"q":"MySQL 中让主键自动递增使用？","o":["IDENTITY","SERIAL ONLY","AUTO_INCREMENT","SEQUENCE()"],"a":2,"e":"AUTO_INCREMENT 列每次插入自动生成递增值。"},
{"id":"sql-1-034","c":"sql","l":1,"q":"VARCHAR 与 CHAR 的区别是？","o":["VARCHAR 变长存储，CHAR 定长存储","CHAR 是变长的","两者完全相同","VARCHAR 只能存数字"],"a":0,"e":"CHAR 不足长度时会填充空格，适合定长数据。"},
{"id":"sql-1-035","c":"sql","l":1,"q":"存储金额最合适的 MySQL 类型是？","o":["FLOAT","DECIMAL","VARCHAR","DOUBLE"],"a":1,"e":"DECIMAL 精确存储小数，浮点类型有精度误差。"},
{"id":"sql-1-036","c":"sql","l":1,"q":"MySQL 中只存储日期（不含时间）的类型是？","o":["TIMESTAMP","DATETIME","TIME","DATE"],"a":3,"e":"DATETIME 和 TIMESTAMP 包含时间部分。"},
{"id":"sql-1-037","c":"sql","l":1,"q":"统计行数的聚合函数是？","o":["NUM","TOTAL","SUM","COUNT"],"a":3,"e":"COUNT(*) 统计所有行。"},
{"id":"sql-1-038","c":"sql","l":1,"q":"求平均值的聚合函数是？","o":["AVERAGE","MEAN","AVG","MID"],"a":2,"e":"AVG 忽略 NULL 值。"},
{"id":"sql-1-039","c":"sql","l":1,"q":"COUNT(*) 与 COUNT(col) 的区别是？","o":["COUNT(col) 不统计 col 为 NULL 的行","COUNT(col) 会去重","完全相同","COUNT(*) 不统计 NULL 行"],"a":0,"e":"去重计数需使用 COUNT(DISTINCT col)。"},
{"id":"sql-1-040","c":"sql","l":1,"q":"AVG(score) 如何处理 NULL 值？","o":["返回 NULL","忽略 NULL","当作 0","报错"],"a":1,"e":"聚合函数（COUNT(*) 除外）会忽略 NULL。"},
{"id":"sql-1-041","c":"sql","l":1,"q":"SUM 对一个所有值都是 NULL 的列求和，结果是？","o":["报错","空字符串","NULL","0"],"a":2,"e":"没有非 NULL 值时 SUM 返回 NULL，可用 COALESCE 转为 0。"},
{"id":"sql-1-042","c":"sql","l":1,"q":"按部门统计人数需要使用？","o":["DISTINCT BY","PARTITION","ORDER BY","GROUP BY"],"a":3,"e":"GROUP BY dept 后对每组使用 COUNT(*)。"},
{"id":"sql-1-043","c":"sql","l":1,"q":"WHERE 与 HAVING 的主要区别是？","o":["HAVING 在分组前过滤","WHERE 只能用于 UPDATE","没有区别","WHERE 在分组前过滤，HAVING 在分组后过滤"],"a":3,"e":"HAVING 可以使用聚合函数作为条件。"},
{"id":"sql-1-044","c":"sql","l":1,"q":"找出员工数超过 5 人的部门，正确的是？","o":["WHERE COUNT(*) > 5","GROUP BY dept HAVING COUNT(*) > 5","HAVING dept > 5","ORDER BY COUNT(*) > 5"],"a":1,"e":"对分组结果按聚合条件过滤必须使用 HAVING。"},
{"id":"sql-1-045","c":"sql","l":1,"q":"WHERE 子句中能直接使用聚合函数吗？","o":["只能用 COUNT","不能","能","只在 MySQL 中能"],"a":1,"e":"WHERE 在分组前执行，此时聚合值尚未计算。"},
{"id":"sql-1-046","c":"sql","l":1,"q":"SELECT 语句逻辑执行顺序中最先执行的是？","o":["FROM","SELECT","WHERE","ORDER BY"],"a":0,"e":"逻辑顺序为 FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT。"},
{"id":"sql-1-047","c":"sql","l":1,"q":"INNER JOIN 返回的是？","o":["左表全部行","两表全部行","两表都匹配的行","右表全部行"],"a":2,"e":"内连接只返回满足连接条件的行。"},
{"id":"sql-1-048","c":"sql","l":1,"q":"LEFT JOIN 时右表无匹配，右表列的值为？","o":["空字符串","该行被丢弃","NULL","0"],"a":2,"e":"左连接保留左表所有行，右表无匹配时填充 NULL。"},
{"id":"sql-1-049","c":"sql","l":1,"q":"RIGHT JOIN 保留的是？","o":["两表的全部行","两表都匹配的行","左表的所有行","右表的所有行"],"a":3,"e":"A RIGHT JOIN B 等价于 B LEFT JOIN A。"},
{"id":"sql-1-050","c":"sql","l":1,"q":"表 A 有 3 行、B 有 4 行，CROSS JOIN 结果有多少行？","o":["12","3","7","4"],"a":0,"e":"交叉连接是笛卡尔积，3 × 4 = 12。"},
{"id":"sql-1-051","c":"sql","l":1,"q":"JOIN 时两表都有 id 列，引用时应该？","o":["直接写 id","无法引用","写 id1","使用表名或别名限定，如 u.id"],"a":3,"e":"有歧义的列名不加限定会报错。"},
{"id":"sql-1-052","c":"sql","l":1,"q":"MySQL 是否原生支持 FULL OUTER JOIN？","o":["支持","只在 InnoDB 中支持","只在 8.0 中支持","不支持，可以用 LEFT JOIN UNION RIGHT JOIN 模拟"],"a":3,"e":"MySQL 至今不支持 FULL OUTER JOIN 语法。"},
{"id":"sql-1-053","c":"sql","l":1,"q":"UNION 与 UNION ALL 的区别是？","o":["两者相同","UNION 会去重，UNION ALL 保留所有行","UNION ALL 会去重","UNION 只能合并两张表"],"a":1,"e":"UNION ALL 无需去重，性能更好。"},
{"id":"sql-1-054","c":"sql","l":1,"q":"使用 UNION 时各 SELECT 需要满足？","o":["表名相同","列数相同且类型兼容","行数相同","列名完全相同"],"a":1,"e":"结果列名取自第一个 SELECT。"},
{"id":"sql-1-055","c":"sql","l":1,"q":"子查询是指？","o":["视图","嵌套在另一个查询中的查询","存储过程","临时表"],"a":1,"e":"子查询可出现在 WHERE、FROM、SELECT 中。"},
{"id":"sql-1-056","c":"sql","l":1,"q":"查询工资高于平均工资的员工，正确的是？","o":["WHERE salary > AVG(salary)","WHERE AVG(salary) < salary","HAVING salary > AVG","WHERE salary > (SELECT AVG(salary) FROM emp)"],"a":3,"e":"WHERE 中不能直接使用聚合函数，需使用标量子查询。"},
{"id":"sql-1-057","c":"sql","l":1,"q":"EXISTS 子查询的判断依据是？","o":["子查询返回的具体值","子查询是否返回至少一行","第一列是否为真","返回行数是否大于 1"],"a":1,"e":"EXISTS 只关心是否有结果行。"},
{"id":"sql-1-058","c":"sql","l":1,"q":"索引的主要作用是？","o":["加快数据检索","保证数据不丢失","加快写入速度","减少存储空间"],"a":0,"e":"索引类似书的目录，但会增加写入开销。"},
{"id":"sql-1-059","c":"sql","l":1,"q":"创建索引的语句是？","o":["ADD INDEX ON t","MAKE INDEX","INDEX CREATE t","CREATE INDEX idx_name ON t (col)"],"a":3,"e":"也可以用 ALTER TABLE t ADD INDEX idx_name (col)。"},
{"id":"sql-1-060","c":"sql","l":1,"q":"MySQL InnoDB 默认的索引结构是？","o":["位图","哈希表","B+ 树","二叉搜索树"],"a":2,"e":"B+ 树适合等值查询、范围查询和排序。"},
{"id":"sql-1-061","c":"sql","l":1,"q":"索引的主要缺点是？","o":["占用空间并降低增删改性能","不能用于排序","降低查询速度","导致数据丢失"],"a":0,"e":"每次写入都需要维护索引结构。"},
{"id":"sql-1-062","c":"sql","l":1,"q":"MySQL InnoDB 中主键会自动创建什么索引？","o":["空间索引","聚簇索引（主键索引）","哈希索引","全文索引"],"a":1,"e":"InnoDB 表的数据按主键组织存储。"},
{"id":"sql-1-063","c":"sql","l":1,"q":"事务的 ACID 中 “A” 代表？","o":["准确性 Accuracy","可用性 Availability","异步 Async","原子性 Atomicity"],"a":3,"e":"原子性指事务中的操作要么全部成功，要么全部回滚。"},
{"id":"sql-1-064","c":"sql","l":1,"q":"ACID 中的 “I” 代表？","o":["隔离性 Isolation","不可变 Immutable","索引 Index","完整性 Integrity"],"a":0,"e":"ACID 即原子性、一致性、隔离性、持久性。"},
{"id":"sql-1-065","c":"sql","l":1,"q":"ACID 中的 “D” 持久性指？","o":["数据不可删除","数据自动备份","事务提交后修改永久保存，即使系统崩溃","事务持续运行"],"a":2,"e":"InnoDB 通过 redo log 保证持久性。"},
{"id":"sql-1-066","c":"sql","l":1,"q":"撤销当前事务所有未提交修改的语句是？","o":["COMMIT","REVOKE","ROLLBACK","SAVEPOINT"],"a":2,"e":"COMMIT 提交使修改永久生效。"},
{"id":"sql-1-067","c":"sql","l":1,"q":"MySQL 中显式开启事务的语句是？","o":["OPEN TRANSACTION","NEW TRANSACTION","START TRANSACTION 或 BEGIN","TRANSACTION ON"],"a":2,"e":"开启后直到 COMMIT 或 ROLLBACK 结束。"},
{"id":"sql-1-068","c":"sql","l":1,"q":"MySQL 默认的 autocommit 设置是？","o":["随机","关闭","开启（每条语句自动提交）","只对 SELECT 开启"],"a":2,"e":"autocommit=1 时每条语句是独立的事务。"},
{"id":"sql-1-069","c":"sql","l":1,"q":"SAVEPOINT 的作用是？","o":["备份数据库","提交事务","锁定表","在事务中设置保存点，可回滚到该点"],"a":3,"e":"ROLLBACK TO SAVEPOINT sp 只回滚保存点之后的操作。"},
{"id":"sql-1-070","c":"sql","l":1,"q":"MySQL InnoDB 默认的事务隔离级别是？","o":["SERIALIZABLE","READ UNCOMMITTED","REPEATABLE READ","READ COMMITTED"],"a":2,"e":"InnoDB 默认是可重复读。"},
{"id":"sql-1-071","c":"sql","l":1,"q":"读到其他事务尚未提交的数据称为？","o":["丢失更新","脏读","幻读","不可重复读"],"a":1,"e":"脏读只会在 READ UNCOMMITTED 级别发生。"},
{"id":"sql-1-072","c":"sql","l":1,"q":"视图（VIEW）是？","o":["物理存储的表副本","索引的一种","基于查询定义的虚拟表","存储过程"],"a":2,"e":"普通视图不存储数据，查询时执行其定义。"},
{"id":"sql-1-073","c":"sql","l":1,"q":"删除视图使用？","o":["DELETE VIEW v","DROP VIEW v","TRUNCATE VIEW v","REMOVE VIEW v"],"a":1,"e":"删除视图不影响基表数据。"},
{"id":"sql-1-074","c":"sql","l":1,"q":"ROUND(3.567, 2) 的结果是？","o":["3.56","3.5","3.57","4"],"a":2,"e":"ROUND 按指定小数位四舍五入。"},
{"id":"sql-1-075","c":"sql","l":1,"q":"MySQL 中 CONCAT('a', NULL, 'b') 的结果是？","o":["'ab'","'aNULLb'","NULL","'a b'"],"a":2,"e":"CONCAT 任一参数为 NULL 时返回 NULL；CONCAT_WS 会跳过 NULL。"},
{"id":"sql-1-076","c":"sql","l":1,"q":"MySQL 中获取字符串字符数的函数是？","o":["CHAR_LENGTH()","SIZE()","COUNT()","LENGTH()（总是字符数）"],"a":0,"e":"LENGTH() 返回字节数，多字节字符时两者不同。"},
{"id":"sql-1-077","c":"sql","l":1,"q":"MySQL 中获取当前日期时间的函数是？","o":["SYSDATE_TIME()","TODAY()","NOW()","GETDATE()"],"a":2,"e":"GETDATE() 是 SQL Server 的函数。"},
{"id":"sql-1-078","c":"sql","l":1,"q":"CASE WHEN 表达式的作用是？","o":["定义循环","实现条件分支取值","创建索引","开启事务"],"a":1,"e":"CASE WHEN cond THEN a ELSE b END。"},
{"id":"sql-1-079","c":"sql","l":1,"q":"WHERE col NOT IN (1, 2, NULL) 返回多少行？","o":["0 行","报错","所有行","返回 col 不等于 1、2 的行"],"a":0,"e":"与 NULL 比较为 UNKNOWN，NOT IN 条件永远不为真。"},
{"id":"sql-1-080","c":"sql","l":1,"q":"NULL = NULL 的结果是？","o":["UNKNOWN（NULL）","TRUE","报错","FALSE"],"a":0,"e":"NULL 表示未知值，比较结果也是未知；MySQL 中可用 <=> 安全比较。"},
{"id":"sql-1-081","c":"sql","l":1,"q":"MySQL 中 NULL <=> NULL 的结果是？","o":["NULL","0","报错","1（真）"],"a":3,"e":"<=> 是 NULL 安全的等值比较运算符。"},
{"id":"sql-1-082","c":"sql","l":1,"q":"在 MySQL 中 ORDER BY 升序时 NULL 值排在？","o":["被过滤掉","随机","最前面","最后面"],"a":2,"e":"MySQL 将 NULL 视为最小值，降序时排在最后。"},
{"id":"sql-1-083","c":"sql","l":1,"q":"GROUP BY 后 SELECT 中的非聚合列在标准 SQL 中应满足？","o":["必须有索引","出现在 GROUP BY 中","可以随意","必须是主键"],"a":1,"e":"MySQL 默认开启 ONLY_FULL_GROUP_BY，违反时报错（存在函数依赖时除外）。"},
{"id":"sql-1-084","c":"sql","l":1,"q":"COUNT(DISTINCT dept) 的含义是？","o":["统计所有行","统计重复值个数","统计 dept 不同非 NULL 值的个数","统计 NULL 个数"],"a":2,"e":"DISTINCT 去重后再计数，NULL 不计入。"},
{"id":"sql-1-085","c":"sql","l":1,"q":"MAX 函数可以用于字符串列吗？","o":["不可以","只能用于数字","可以，按排序规则比较","只能用于日期"],"a":2,"e":"MAX/MIN 适用于可比较的类型。"},
{"id":"sql-1-086","c":"sql","l":1,"q":"LEFT JOIN 查找“没有订单的客户”的常用写法是？","o":["RIGHT JOIN ... WHERE c.id IS NULL","LEFT JOIN orders o ... WHERE o.id IS NULL","CROSS JOIN","INNER JOIN ... WHERE o.id IS NULL"],"a":1,"e":"筛选右表主键为 NULL 的行即为无匹配记录。"},
{"id":"sql-1-087","c":"sql","l":1,"q":"自连接通常用于？","o":["查询同一张表中的层级关系，如员工及其上级","创建索引","删除重复表","合并两个数据库"],"a":0,"e":"同一张表使用不同别名连接自身。"},
{"id":"sql-1-088","c":"sql","l":1,"q":"INSERT INTO t (a, b) VALUES (1, 2), (3, 4) 的效果是？","o":["插入一行四列","一次插入两行","报错","只插入第一行"],"a":1,"e":"多值 INSERT 比逐条插入效率更高。"},
{"id":"sql-1-089","c":"sql","l":1,"q":"INSERT INTO t2 SELECT ... FROM t1 的作用是？","o":["创建新表","删除 t1","把查询结果插入另一张表","更新 t2"],"a":2,"e":"列数与类型需要匹配目标列。"},
{"id":"sql-1-090","c":"sql","l":1,"q":"MySQL 中 CREATE TABLE t2 LIKE t1 的作用是？","o":["复制 t1 的表结构（含索引），不复制数据","复制结构和数据","创建视图","重命名表"],"a":0,"e":"CREATE TABLE t2 AS SELECT 会复制数据但不复制索引。"},
{"id":"sql-1-091","c":"sql","l":1,"q":"修改表名的语句是？","o":["ALTER NAME a b","CHANGE TABLE a b","UPDATE TABLE a NAME b","RENAME TABLE a TO b"],"a":3,"e":"也可以用 ALTER TABLE a RENAME TO b。"},
{"id":"sql-1-092","c":"sql","l":1,"q":"DDL 指的是？","o":["事务控制语言","数据操作语言，如 INSERT","数据定义语言，如 CREATE、ALTER、DROP","数据控制语言，如 GRANT"],"a":2,"e":"DML 包括 SELECT、INSERT、UPDATE、DELETE。"},
{"id":"sql-1-093","c":"sql","l":1,"q":"授予用户权限使用的语句是？","o":["GRANT","ALLOW","GIVE","PERMIT"],"a":0,"e":"REVOKE 用于收回权限，二者属于 DCL。"},
{"id":"sql-1-094","c":"sql","l":1,"q":"数据库第一范式（1NF）的要求是？","o":["消除部分依赖","每列都是不可再分的原子值","必须有外键","消除传递依赖"],"a":1,"e":"例如不应在一列中用逗号存储多个电话号码。"},
{"id":"sql-1-095","c":"sql","l":1,"q":"第三范式（3NF）主要消除？","o":["NULL 值","非主属性对主键的传递依赖","重复行","多值属性"],"a":1,"e":"2NF 消除部分依赖，3NF 进一步消除传递依赖。"},
{"id":"sql-1-096","c":"sql","l":1,"q":"SELECT 'abc' = 'ABC' 在 MySQL 默认排序规则下的结果是？","o":["0（假）","1（真）","报错","NULL"],"a":1,"e":"默认的 *_ci 排序规则不区分大小写。"},
{"id":"sql-1-097","c":"sql","l":1,"q":"SELECT COUNT(*) FROM t WHERE 1 = 0 的结果是？","o":["报错","空结果集","NULL","0"],"a":3,"e":"没有 GROUP BY 的聚合查询总是返回一行，COUNT 返回 0。"},
{"id":"sql-1-098","c":"sql","l":1,"q":"主键使用自增整数而不是随机 UUID 的好处（InnoDB）是？","o":["插入按顺序追加，减少页分裂","支持更多行","更安全","节省网络带宽"],"a":0,"e":"随机主键会导致 B+ 树频繁页分裂和碎片。"},
{"id":"sql-1-099","c":"sql","l":1,"q":"MySQL 中 IF(cond, a, b) 函数的作用是？","o":["创建条件索引","cond 为真返回 a，否则返回 b","判断表是否存在","循环执行"],"a":1,"e":"它是 MySQL 特有函数，标准写法是 CASE WHEN。"},
{"id":"sql-1-100","c":"sql","l":1,"q":"SELECT DISTINCT a, b 去重的依据是？","o":["报错","只按 a 去重","只按 b 去重","a 和 b 组合起来相同才视为重复"],"a":3,"e":"DISTINCT 作用于整行选取的所有列。"},
{"id":"sql-2-001","c":"sql","l":2,"q":"LEFT JOIN 中把右表过滤条件写在 WHERE 而非 ON 中，常见后果是？","o":["语法错误","没有区别","结果实际上变成类似内连接","返回笛卡尔积"],"a":2,"e":"WHERE 过滤掉右表为 NULL 的行，丢失了保留左表行的效果。"},
{"id":"sql-2-002","c":"sql","l":2,"q":"A LEFT JOIN B ON a.id = b.aid，若 A 的一行匹配 B 的 3 行，结果中该行出现几次？","o":["4 次","0 次","3 次","1 次"],"a":2,"e":"一对多连接会让左表行重复，聚合时需注意重复计数。"},
{"id":"sql-2-003","c":"sql","l":2,"q":"JOIN ... USING (id) 与 ON a.id = b.id 的区别是？","o":["USING 只能用于 LEFT JOIN","USING 要求两表列名相同，结果中该列只出现一次","没有任何区别","USING 性能更差"],"a":1,"e":"USING 是等值连接的简写。"},
{"id":"sql-2-004","c":"sql","l":2,"q":"NATURAL JOIN 的风险是？","o":["不能返回数据","只能连接两张表","性能极差","自动按所有同名列连接，表结构变化时结果可能悄然改变"],"a":3,"e":"实际开发中应显式写出连接条件。"},
{"id":"sql-2-005","c":"sql","l":2,"q":"多表连接时 FROM a JOIN b ON ... JOIN c ON ...，c 的连接条件可以引用？","o":["只能引用 b","a 和 b 的列","只能引用 a","不能引用其他表"],"a":1,"e":"连接按顺序构建，后续条件可引用之前出现的表。"},
{"id":"sql-2-006","c":"sql","l":2,"q":"查询每个部门及其员工数（包括没有员工的部门），应使用？","o":["员工表 LEFT JOIN 部门表","部门表 LEFT JOIN 员工表，再 COUNT(e.id)","INNER JOIN 后 COUNT(*)","CROSS JOIN"],"a":1,"e":"COUNT(e.id) 对无员工部门返回 0，COUNT(*) 会返回 1。"},
{"id":"sql-2-007","c":"sql","l":2,"q":"自连接查询“员工及其经理姓名”时，经理为空的员工也要显示，应用？","o":["UNION","INNER JOIN emp m ON e.manager_id = m.id","LEFT JOIN emp m ON e.manager_id = m.id","CROSS JOIN emp m"],"a":2,"e":"内连接会丢掉 manager_id 为 NULL 的员工。"},
{"id":"sql-2-008","c":"sql","l":2,"q":"非等值连接的例子是？","o":["NATURAL JOIN","JOIN d ON e.dept_id = d.id","JOIN grade g ON e.salary BETWEEN g.low AND g.high","USING (id)"],"a":2,"e":"连接条件不一定是等号。"},
{"id":"sql-2-009","c":"sql","l":2,"q":"在 GROUP BY 中，NULL 值的处理方式是？","o":["报错","NULL 行被丢弃","所有 NULL 被归为同一组","每个 NULL 单独成组"],"a":2,"e":"分组时 NULL 被视为相同的值。"},
{"id":"sql-2-010","c":"sql","l":2,"q":"GROUP BY a, b 的分组依据是？","o":["先 a 后 b 分别分组两次","只按 a","a 和 b 的组合","只按 b"],"a":2,"e":"每个不同的 (a, b) 组合构成一组。"},
{"id":"sql-2-011","c":"sql","l":2,"q":"MySQL 8.0 中 GROUP BY 是否还隐式排序？","o":["随机","总是降序","不再隐式排序，需要显式 ORDER BY","总是升序"],"a":2,"e":"MySQL 8.0 移除了 GROUP BY 的隐式排序。"},
{"id":"sql-2-012","c":"sql","l":2,"q":"WITH ROLLUP 的作用是？","o":["锁定表","递归查询","在分组结果中额外生成小计和总计行","去除重复"],"a":2,"e":"汇总行中的分组列显示为 NULL，可用 GROUPING() 区分。"},
{"id":"sql-2-013","c":"sql","l":2,"q":"HAVING 中可以使用 SELECT 中定义的别名吗（MySQL）？","o":["可以，MySQL 允许","不可以","只在严格模式下可以","只能用于 COUNT"],"a":0,"e":"这是 MySQL 扩展；标准 SQL 中应重复写表达式。"},
{"id":"sql-2-014","c":"sql","l":2,"q":"WHERE 中可以使用 SELECT 中定义的列别名吗？","o":["只在 MySQL 中可以","不可以","可以","只能用于数字列"],"a":1,"e":"WHERE 在 SELECT 之前执行，别名尚未定义。"},
{"id":"sql-2-015","c":"sql","l":2,"q":"统计每个用户订单总额，并只显示总额大于 1000 的用户，正确写法是？","o":["WHERE SUM(amount) > 1000 GROUP BY user_id","GROUP BY user_id WHERE SUM(amount) > 1000","HAVING amount > 1000","GROUP BY user_id HAVING SUM(amount) > 1000"],"a":3,"e":"聚合条件必须写在 HAVING 中。"},
{"id":"sql-2-016","c":"sql","l":2,"q":"SUM(CASE WHEN status = 'paid' THEN 1 ELSE 0 END) 的作用是？","o":["筛选 paid 行","统计 status 为 paid 的行数","求 status 之和","报错"],"a":1,"e":"条件聚合可以在一次扫描中统计多种指标。"},
{"id":"sql-2-017","c":"sql","l":2,"q":"MySQL 的 GROUP_CONCAT 的作用是？","o":["合并表","将分组内的值拼接成一个字符串","拼接列名","分组计数"],"a":1,"e":"默认分隔符为逗号，长度受 group_concat_max_len 限制。"},
{"id":"sql-2-018","c":"sql","l":2,"q":"COUNT(1) 与 COUNT(*) 在 InnoDB 中的区别是？","o":["COUNT(1) 不统计 NULL 行","COUNT(1) 只统计第一列","语义和性能基本相同","COUNT(*) 更慢很多"],"a":2,"e":"两者都统计行数，MySQL 官方说明处理方式相同。"},
{"id":"sql-2-019","c":"sql","l":2,"q":"InnoDB 中 SELECT COUNT(*) FROM t 为什么不像 MyISAM 那样直接返回？","o":["因为有外键","InnoDB 不支持 COUNT","MVCC 下不同事务可见的行数不同，需要扫描","没有主键"],"a":2,"e":"InnoDB 会选择最小的可用索引进行扫描计数。"},
{"id":"sql-2-020","c":"sql","l":2,"q":"salary > ALL (SELECT salary FROM emp WHERE dept = 10) 的含义是？","o":["大于子查询结果中的所有值","大于其中任意一个","等于其中某个值","小于最小值"],"a":0,"e":"子查询结果为空时 > ALL 为真。"},
{"id":"sql-2-021","c":"sql","l":2,"q":"salary > ANY (子查询) 等价于？","o":["大于最大值","等于所有值","大于子查询结果的最小值","小于最小值"],"a":2,"e":"ANY 与 SOME 同义，满足任意一个即可。"},
{"id":"sql-2-022","c":"sql","l":2,"q":"= 比较子查询时，子查询返回多行会怎样？","o":["自动转为 IN","取第一行","报错","取最大值"],"a":2,"e":"多行结果应使用 IN、ANY 或 ALL。"},
{"id":"sql-2-023","c":"sql","l":2,"q":"相关子查询的特点是？","o":["引用了外层查询的列","不能使用 WHERE","只执行一次","只能出现在 FROM 中"],"a":0,"e":"逻辑上对外层每一行都要计算一次。"},
{"id":"sql-2-024","c":"sql","l":2,"q":"FROM 子句中的子查询（派生表）在 MySQL 中必须？","o":["有别名","是相关子查询","有 LIMIT","有 ORDER BY"],"a":0,"e":"如 SELECT * FROM (SELECT ...) AS t。"},
{"id":"sql-2-025","c":"sql","l":2,"q":"查询每个部门工资最高的员工，可以使用？","o":["ORDER BY salary LIMIT 1","HAVING MAX(salary)","WHERE (dept, salary) IN (SELECT dept, MAX(salary) FROM emp GROUP BY dept)","SELECT dept, MAX(salary), name FROM emp GROUP BY dept"],"a":2,"e":"直接选 name 在 ONLY_FULL_GROUP_BY 下报错且结果不确定。"},
{"id":"sql-2-026","c":"sql","l":2,"q":"NOT EXISTS 与 NOT IN 处理 NULL 的区别是？","o":["NOT EXISTS 遇到 NULL 报错","子查询含 NULL 时 NOT IN 返回空，NOT EXISTS 不受影响","NOT IN 会忽略 NULL","两者完全一致"],"a":1,"e":"因此反连接推荐使用 NOT EXISTS 或 LEFT JOIN ... IS NULL。"},
{"id":"sql-2-027","c":"sql","l":2,"q":"EXISTS 子查询中 SELECT 1 与 SELECT * 的区别是？","o":["SELECT 1 会报错","SELECT * 更慢很多","结果不同","没有区别，EXISTS 只判断是否有行"],"a":3,"e":"EXISTS 不关心返回的列。"},
{"id":"sql-2-028","c":"sql","l":2,"q":"标量子查询是指？","o":["返回多行的子查询","FROM 中的子查询","只返回一行一列的子查询","带 EXISTS 的子查询"],"a":2,"e":"标量子查询可以出现在 SELECT 列表或表达式中。"},
{"id":"sql-2-029","c":"sql","l":2,"q":"MySQL 8.0 中 WITH 子句（CTE）的作用是？","o":["开启事务","创建索引","定义可在主查询中引用的命名临时结果集","创建永久表"],"a":2,"e":"CTE 让复杂查询更易读，同一 CTE 可多次引用。"},
{"id":"sql-2-030","c":"sql","l":2,"q":"UPDATE t SET a = a + 1 WHERE id IN (SELECT id FROM t WHERE ...) 在 MySQL 中会怎样？","o":["死锁","报错，不能在子查询中引用正在更新的同一张表","只更新一行","正常执行"],"a":1,"e":"可以用派生表包一层或改写为 JOIN 规避（错误 1093）。"},
{"id":"sql-2-031","c":"sql","l":2,"q":"MySQL 多表 UPDATE 的写法是？","o":["UPDATE a JOIN b ON a.id = b.aid SET a.x = b.y","UPDATE a FROM b","不支持","UPDATE a, b SET ... FROM ..."],"a":0,"e":"MySQL 支持多表 UPDATE 和 DELETE 语法。"},
{"id":"sql-2-032","c":"sql","l":2,"q":"删除重复数据只保留 id 最小的一条，可以用？","o":["TRUNCATE t","DELETE FROM t GROUP BY email","DELETE DISTINCT FROM t","DELETE t1 FROM t t1 JOIN t t2 ON t1.email = t2.email AND t1.id > t2.id"],"a":3,"e":"自连接找出存在更小 id 的重复行并删除。"},
{"id":"sql-2-033","c":"sql","l":2,"q":"对联合索引 (a, b, c)，哪个条件不能利用最左前缀进行查找？","o":["WHERE a = 1","WHERE a = 1 AND b = 2 AND c = 3","WHERE b = 2 AND c = 3","WHERE a = 1 AND b = 2"],"a":2,"e":"缺少最左列 a 时无法按该索引定位（8.0 的跳跃扫描是特例）。"},
{"id":"sql-2-034","c":"sql","l":2,"q":"WHERE b = 2 AND a = 1 能否使用联合索引 (a, b)？","o":["报错","能，优化器会调整条件顺序","只能用到 b","不能"],"a":1,"e":"最左前缀看的是条件是否覆盖列，与书写顺序无关。"},
{"id":"sql-2-035","c":"sql","l":2,"q":"联合索引 (a, b) 下 WHERE a > 1 AND b = 2，b 能否用于索引定位？","o":["能完全利用","只能用 b","两列都无法使用","通常不能，范围条件后的列无法继续用于定位"],"a":3,"e":"但 b 仍可以通过索引条件下推（ICP）过滤。"},
{"id":"sql-2-036","c":"sql","l":2,"q":"以下哪种写法通常会导致索引失效？","o":["WHERE id = 5","WHERE name = 'Tom'","WHERE name LIKE 'Tom%'","WHERE name LIKE '%Tom'"],"a":3,"e":"前导通配符无法利用 B+ 树的有序性。"},
{"id":"sql-2-037","c":"sql","l":2,"q":"对索引列使用函数，如 WHERE YEAR(created_at) = 2024，会？","o":["无法直接使用该列的普通索引","报错","加速查询","正常使用索引"],"a":0,"e":"可改写为范围条件，或在 8.0 中使用函数索引。"},
{"id":"sql-2-038","c":"sql","l":2,"q":"phone 列是 VARCHAR 类型并有索引，WHERE phone = 13800000000 会？","o":["正常走索引","报错","只扫描一行","发生隐式类型转换，无法使用该索引"],"a":3,"e":"字符串列与数字比较时会把列转为数字，应加引号。"},
{"id":"sql-2-039","c":"sql","l":2,"q":"InnoDB 二级索引的叶子节点存储的是？","o":["完整的行数据","索引列的值和主键值","行的物理地址","只有索引列"],"a":1,"e":"通过二级索引查到主键后再查聚簇索引称为回表。"},
{"id":"sql-2-040","c":"sql","l":2,"q":"覆盖索引是指？","o":["全文索引","查询所需列全部包含在索引中，无需回表","主键索引","唯一索引"],"a":1,"e":"EXPLAIN 的 Extra 显示 Using index 即使用了覆盖索引。"},
{"id":"sql-2-041","c":"sql","l":2,"q":"唯一索引与普通索引的主要区别是？","o":["唯一索引更慢很多","唯一索引不能有 NULL","唯一索引要求值不重复（NULL 除外）","普通索引不能用于查询"],"a":2,"e":"唯一索引在插入时需检查唯一性，无法使用 change buffer。"},
{"id":"sql-2-042","c":"sql","l":2,"q":"区分度低的列（如性别）通常不适合单独建索引，原因是？","o":["占用空间太少","会导致数据错误","不能建索引","通过索引过滤的行太多，优化器可能选择全表扫描"],"a":3,"e":"索引选择性 = 不同值数量 / 总行数，越高越好。"},
{"id":"sql-2-043","c":"sql","l":2,"q":"前缀索引 INDEX(name(10)) 的缺点是？","o":["只能用于数字","占用更多空间","无法用于覆盖索引和 ORDER BY 排序","不能加速查询"],"a":2,"e":"前缀索引节省空间，但索引中只有部分内容。"},
{"id":"sql-2-044","c":"sql","l":2,"q":"EXPLAIN 命令的作用是？","o":["查看 SQL 的执行计划","显示表定义","优化表结构","执行 SQL 并解释结果"],"a":0,"e":"可以看到访问类型、使用的索引和预估行数等。"},
{"id":"sql-2-045","c":"sql","l":2,"q":"EXPLAIN 中 type 列为 ALL 表示？","o":["全表扫描","常量查找","最优访问","使用了所有索引"],"a":0,"e":"一般应尽量优化到 range、ref 或更好。"},
{"id":"sql-2-046","c":"sql","l":2,"q":"EXPLAIN 的 type 列中，以下哪种性能通常最好？","o":["range","ALL","const","index"],"a":2,"e":"大致顺序为 system > const > eq_ref > ref > range > index > ALL。"},
{"id":"sql-2-047","c":"sql","l":2,"q":"EXPLAIN 的 key 列表示？","o":["实际使用的索引","主键名","可能使用的索引","索引长度"],"a":0,"e":"possible_keys 才是可能使用的索引。"},
{"id":"sql-2-048","c":"sql","l":2,"q":"EXPLAIN 中 Extra 出现 Using filesort 表示？","o":["需要额外的排序操作，无法利用索引顺序","使用了文件索引","使用了覆盖索引","查询错误"],"a":0,"e":"可通过让 ORDER BY 与索引顺序一致来避免。"},
{"id":"sql-2-049","c":"sql","l":2,"q":"EXPLAIN 中 Extra 出现 Using temporary 表示？","o":["使用了临时索引","使用了临时表，常见于 GROUP BY、DISTINCT 或 UNION","使用了缓存","事务回滚"],"a":1,"e":"临时表可能带来额外开销。"},
{"id":"sql-2-050","c":"sql","l":2,"q":"ORDER BY 能利用联合索引 (a, b) 避免 filesort 的条件是？","o":["ORDER BY b, a","ORDER BY a DESC, b ASC（MySQL 5.7）","ORDER BY b","如 WHERE a = 1 ORDER BY b"],"a":3,"e":"排序列需符合索引顺序，且前导列为等值条件。"},
{"id":"sql-2-051","c":"sql","l":2,"q":"深分页 LIMIT 1000000, 10 慢的原因是？","o":["LIMIT 不能用索引","需要先扫描并丢弃前 100 万行","返回了太多数据","数据库会锁表"],"a":1,"e":"可用“记住上次最大 id”的游标分页或延迟关联优化。"},
{"id":"sql-2-052","c":"sql","l":2,"q":"优化深分页的常用写法是？","o":["去掉 ORDER BY","使用 SELECT *","增大 LIMIT","WHERE id > 上一页最大 id ORDER BY id LIMIT 10"],"a":3,"e":"基于索引定位起点，避免扫描大量偏移行。"},
{"id":"sql-2-053","c":"sql","l":2,"q":"OR 连接两个不同列的条件时，要高效使用索引通常需要？","o":["无法优化","改用 HAVING","只需一列有索引","两列都有索引（可能使用 index merge）或改写为 UNION"],"a":3,"e":"若一列无索引，可能导致全表扫描。"},
{"id":"sql-2-054","c":"sql","l":2,"q":"SELECT * 不推荐的原因不包括？","o":["无法使用覆盖索引","表结构变化可能影响程序","会导致 SQL 语法错误","传输不需要的数据"],"a":2,"e":"只查询需要的列是良好实践。"},
{"id":"sql-2-055","c":"sql","l":2,"q":"大表 JOIN 时，连接列上应该？","o":["建立索引","避免索引","使用不同的数据类型","使用函数包装"],"a":0,"e":"被驱动表的连接列有索引时可以使用索引查找。"},
{"id":"sql-2-056","c":"sql","l":2,"q":"脏读、不可重复读、幻读中，READ COMMITTED 级别可以避免？","o":["幻读","脏读","不可重复读","全部"],"a":1,"e":"RC 只读取已提交的数据，但同一事务内两次读取可能不同。"},
{"id":"sql-2-057","c":"sql","l":2,"q":"同一事务中两次读取同一行，因其他事务提交修改而结果不同，称为？","o":["幻读","不可重复读","死锁","脏读"],"a":1,"e":"不可重复读针对同一行的修改。"},
{"id":"sql-2-058","c":"sql","l":2,"q":"同一事务中两次范围查询，第二次多出了其他事务插入的行，称为？","o":["脏读","丢失更新","幻读","不可重复读"],"a":2,"e":"InnoDB 在 RR 下通过 MVCC 快照和间隙锁很大程度避免幻读。"},
{"id":"sql-2-059","c":"sql","l":2,"q":"能避免脏读、不可重复读和幻读的标准隔离级别是？","o":["SERIALIZABLE","READ COMMITTED","REPEATABLE READ","READ UNCOMMITTED"],"a":0,"e":"SERIALIZABLE 使事务串行化执行，代价最高。"},
{"id":"sql-2-060","c":"sql","l":2,"q":"MySQL 中查看当前会话隔离级别的变量（8.0）是？","o":["@@session_lock","@@isolation","@@tx_level","@@transaction_isolation"],"a":3,"e":"5.7 中也可用 @@tx_isolation（8.0 已移除）。"},
{"id":"sql-2-061","c":"sql","l":2,"q":"设置当前会话隔离级别为读已提交的语句是？","o":["SET ISOLATION = RC","SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED","SET LOCK LEVEL 2","ALTER SESSION RC"],"a":1,"e":"不加 SESSION 时只对下一个事务生效。"},
{"id":"sql-2-062","c":"sql","l":2,"q":"InnoDB 中 DDL 语句（如 ALTER TABLE）对当前事务的影响是？","o":["会回滚当前事务","没有影响","会隐式提交当前事务","会挂起事务"],"a":2,"e":"MySQL 的 DDL 会导致隐式提交，不能被回滚。"},
{"id":"sql-2-063","c":"sql","l":2,"q":"InnoDB 中普通 SELECT（不加锁）在 RR 级别下读取的是？","o":["加排他锁读","快照读（一致性读）","加共享锁读","当前读"],"a":1,"e":"普通 SELECT 通过 MVCC 读取快照，不加锁。"},
{"id":"sql-2-064","c":"sql","l":2,"q":"SELECT ... FOR UPDATE 的作用是？","o":["对读取的行加排他锁（当前读）","加共享锁","创建视图","只读查询"],"a":0,"e":"锁在事务提交或回滚时释放。"},
{"id":"sql-2-065","c":"sql","l":2,"q":"SELECT ... FOR SHARE（8.0，旧写法 LOCK IN SHARE MODE）加的是？","o":["无锁","共享锁","表锁","排他锁"],"a":1,"e":"共享锁之间兼容，但会阻塞其他事务加排他锁。"},
{"id":"sql-2-066","c":"sql","l":2,"q":"InnoDB 的行锁实际是加在？","o":["索引记录上","数据页上","整张表上","物理行地址上"],"a":0,"e":"如果查询无法使用索引，可能需要锁住扫描过的大量记录。"},
{"id":"sql-2-067","c":"sql","l":2,"q":"UPDATE 的 WHERE 条件列没有索引时，InnoDB 在 RR 级别下会？","o":["扫描全表，对扫描到的所有记录加锁，效果接近锁表","不加锁","报错","只锁一行"],"a":0,"e":"因此更新条件列应建立合适的索引。"},
{"id":"sql-2-068","c":"sql","l":2,"q":"死锁发生时 InnoDB 的处理方式是？","o":["永久等待","重启数据库","回滚所有事务","检测到死锁后回滚其中一个代价较小的事务"],"a":3,"e":"被回滚的事务收到 1213 错误，应用应重试。"},
{"id":"sql-2-069","c":"sql","l":2,"q":"降低死锁概率的做法不包括？","o":["使用合适的索引减少锁范围","按相同顺序访问资源","缩短事务","在事务中尽量持有锁更长时间"],"a":3,"e":"大事务和不一致的加锁顺序都会增加死锁风险。"},
{"id":"sql-2-070","c":"sql","l":2,"q":"innodb_lock_wait_timeout 参数的作用是？","o":["死锁检测间隔","查询超时时间","连接超时时间","行锁等待的超时时间"],"a":3,"e":"默认 50 秒，超时后语句报错但事务默认不回滚。"},
{"id":"sql-2-071","c":"sql","l":2,"q":"乐观锁的常见实现方式是？","o":["LOCK TABLES","SELECT ... FOR UPDATE","版本号字段：UPDATE ... SET version = version + 1 WHERE id = ? AND version = ?","SERIALIZABLE 隔离级别"],"a":2,"e":"更新影响行数为 0 时说明数据被别人修改过。"},
{"id":"sql-2-072","c":"sql","l":2,"q":"悲观锁的典型实现是？","o":["CAS 重试","版本号比对","时间戳比较","SELECT ... FOR UPDATE"],"a":3,"e":"悲观锁假设冲突会发生，提前加锁。"},
{"id":"sql-2-073","c":"sql","l":2,"q":"InnoDB 的 redo log 用于保证？","o":["原子性回滚","主从复制","查询缓存","持久性，崩溃后恢复已提交的修改"],"a":3,"e":"redo log 是物理日志，采用 WAL（先写日志）。"},
{"id":"sql-2-074","c":"sql","l":2,"q":"InnoDB 的 undo log 用于？","o":["记录慢查询","崩溃后重做","主从复制","事务回滚和 MVCC 的历史版本"],"a":3,"e":"undo log 记录修改前的数据。"},
{"id":"sql-2-075","c":"sql","l":2,"q":"MySQL 的 binlog 主要用于？","o":["缓存查询结果","事务回滚","主从复制和基于时间点的恢复","MVCC"],"a":2,"e":"binlog 是 Server 层的逻辑日志，所有引擎共用。"},
{"id":"sql-2-076","c":"sql","l":2,"q":"MySQL InnoDB 中 VARCHAR(100) 中的 100 指的是？","o":["最多 100 字节","固定 100 字节","最多 100 个字符","最多 100 行"],"a":2,"e":"MySQL 5.0 起 VARCHAR(n) 的 n 表示字符数。"},
{"id":"sql-2-077","c":"sql","l":2,"q":"utf8mb4 与 utf8（utf8mb3）的区别是？","o":["utf8 支持更多字符","utf8mb4 支持 4 字节字符，如 emoji","两者完全相同","utf8mb4 不支持中文"],"a":1,"e":"MySQL 8.0 的默认字符集是 utf8mb4。"},
{"id":"sql-2-078","c":"sql","l":2,"q":"INT(11) 中的 11 表示？","o":["最大值为 11","占用 11 字节","最多 11 位数字","显示宽度，与存储范围无关"],"a":3,"e":"INT 总是 4 字节；8.0.17 起显示宽度已被弃用。"},
{"id":"sql-2-079","c":"sql","l":2,"q":"TIMESTAMP 与 DATETIME 的区别是？","o":["两者完全相同","TIMESTAMP 受时区影响且范围到 2038 年","DATETIME 受时区影响","TIMESTAMP 范围更大"],"a":1,"e":"TIMESTAMP 以 UTC 存储，读取时按会话时区转换。"},
{"id":"sql-2-080","c":"sql","l":2,"q":"INSERT ... ON DUPLICATE KEY UPDATE 的作用是？","o":["忽略重复行","删除重复行后插入","主键或唯一键冲突时转为更新","报错"],"a":2,"e":"这是 MySQL 实现“存在则更新，不存在则插入”的常用方式。"},
{"id":"sql-2-081","c":"sql","l":2,"q":"REPLACE INTO 在唯一键冲突时的行为是？","o":["更新冲突行的部分列","先删除旧行再插入新行","报错","忽略插入"],"a":1,"e":"删除再插入可能导致自增 ID 变化并触发删除逻辑。"},
{"id":"sql-2-082","c":"sql","l":2,"q":"INSERT IGNORE 遇到唯一键冲突时会？","o":["忽略该行并产生警告","覆盖旧行","插入重复行","报错终止"],"a":0,"e":"IGNORE 也会把部分错误降级为警告，需谨慎使用。"},
{"id":"sql-2-083","c":"sql","l":2,"q":"存储过程与函数的区别（MySQL）是？","o":["函数必须返回一个值，可在 SQL 表达式中使用","函数可以用 CALL 调用","存储过程必须返回值","两者完全相同"],"a":0,"e":"存储过程通过 CALL 调用，可有多个 OUT 参数。"},
{"id":"sql-2-084","c":"sql","l":2,"q":"触发器（TRIGGER）是？","o":["索引类型","在表上发生 INSERT/UPDATE/DELETE 时自动执行的程序","视图","定时任务"],"a":1,"e":"MySQL 支持 BEFORE 和 AFTER 两种触发时机。"},
{"id":"sql-2-085","c":"sql","l":2,"q":"COALESCE(a, b, c) 返回？","o":["所有参数之和","最后一个参数","第一个非 NULL 的参数","NULL 的个数"],"a":2,"e":"所有参数都为 NULL 时返回 NULL。"},
{"id":"sql-2-086","c":"sql","l":2,"q":"NULLIF(a, b) 的作用是？","o":["a = b 时返回 NULL，否则返回 a","a 为 NULL 时返回 b","比较 a 和 b 的大小","总是返回 NULL"],"a":0,"e":"常用于避免除以零：x / NULLIF(y, 0)。"},
{"id":"sql-2-087","c":"sql","l":2,"q":"MySQL 中 SELECT 1 / 0 的结果（默认 sql_mode 下）是？","o":["NULL（并可能产生警告）","Infinity","0","报错终止"],"a":0,"e":"严格模式下 INSERT/UPDATE 中除零会报错（ERROR_FOR_DIVISION_BY_ZERO）。"},
{"id":"sql-2-088","c":"sql","l":2,"q":"DATE_FORMAT(NOW(), '%Y-%m-%d') 的作用是？","o":["解析日期","获取星期","计算日期差","把当前时间格式化为年-月-日字符串"],"a":3,"e":"%Y 四位年份，%m 两位月份，%d 两位日期。"},
{"id":"sql-2-089","c":"sql","l":2,"q":"DATEDIFF('2024-03-10', '2024-03-01') 的结果是？","o":["-9","1","10","9"],"a":3,"e":"DATEDIFF(a, b) 返回 a - b 的天数。"},
{"id":"sql-2-090","c":"sql","l":2,"q":"UNION 中每个 SELECT 的 ORDER BY 应该怎么写才对整体结果排序？","o":["不能排序","在最后一个 SELECT 之后写一个 ORDER BY","只在第一个 SELECT 写","每个 SELECT 都写"],"a":1,"e":"对单个子查询排序需要加括号并配合 LIMIT 才有意义。"},
{"id":"sql-2-091","c":"sql","l":2,"q":"视图可以更新（UPDATE）的条件通常是？","o":["视图都不能更新","视图与基表行一一对应，不含聚合、DISTINCT、GROUP BY 等","只有包含 JOIN 的视图","任何视图都可以"],"a":1,"e":"WITH CHECK OPTION 可确保更新后的行仍满足视图条件。"},
{"id":"sql-2-092","c":"sql","l":2,"q":"MySQL 8.0 移除了哪个功能？","o":["存储过程","查询缓存（Query Cache）","外键","视图"],"a":1,"e":"查询缓存在高并发写入场景下容易成为瓶颈，已在 8.0 中移除。"},
{"id":"sql-2-093","c":"sql","l":2,"q":"慢查询日志用于？","o":["记录所有错误","记录 binlog","记录执行时间超过 long_query_time 的 SQL","记录连接信息"],"a":2,"e":"配合 EXPLAIN 定位和优化慢 SQL。"},
{"id":"sql-2-094","c":"sql","l":2,"q":"连接查询中“小表驱动大表”的含义是？","o":["使用 RIGHT JOIN","小表必须放在 FROM 最后","用结果集较小的表作为驱动表，减少被驱动表的查找次数","大表必须先查"],"a":2,"e":"被驱动表连接列有索引时效果最好，优化器通常会自动选择。"},
{"id":"sql-2-095","c":"sql","l":2,"q":"InnoDB 自增锁模式 innodb_autoinc_lock_mode 在 8.0 中的默认值是？","o":["2（交错模式）","1（连续模式）","3","0（传统模式）"],"a":0,"e":"8.0 默认 binlog 格式为 ROW，因此默认使用并发性更好的交错模式。"},
{"id":"sql-2-096","c":"sql","l":2,"q":"事务回滚后，已分配的 AUTO_INCREMENT 值会？","o":["被回收重用","重置为 1","不会回收，导致 ID 出现空洞","报错"],"a":2,"e":"自增 ID 不保证连续。"},
{"id":"sql-2-097","c":"sql","l":2,"q":"索引条件下推（ICP）的作用是？","o":["自动创建索引","在存储引擎层用索引中的列提前过滤，减少回表次数","把 WHERE 推到 HAVING","把查询推送到从库"],"a":1,"e":"EXPLAIN 的 Extra 显示 Using index condition 表示使用了 ICP。"},
{"id":"sql-2-098","c":"sql","l":2,"q":"MySQL 中 LIKE 'abc%' 能使用索引的原因是？","o":["使用了全文索引","LIKE 总是使用索引","前缀确定，可转为范围扫描","只用于数字"],"a":2,"e":"它相当于范围 'abc' <= col < 'abd'。"},
{"id":"sql-2-099","c":"sql","l":2,"q":"CHAR_LENGTH('数据库') 在 utf8mb4 下的结果是？","o":["3","12","6","9"],"a":0,"e":"CHAR_LENGTH 返回字符数；LENGTH 返回字节数，结果为 9。"},
{"id":"sql-2-100","c":"sql","l":2,"q":"外键约束 ON DELETE CASCADE 的作用是？","o":["禁止删除父表行","删除父表行时自动删除子表中引用它的行","把子表外键设为 NULL","删除整张子表"],"a":1,"e":"SET NULL 会把子表外键置空；默认 RESTRICT 拒绝删除。"},
{"id":"sql-3-001","c":"sql","l":3,"q":"MySQL 从哪个版本开始支持窗口函数？","o":["5.7","5.5","5.6","8.0"],"a":3,"e":"窗口函数和 CTE 都是 MySQL 8.0 引入的。"},
{"id":"sql-3-002","c":"sql","l":3,"q":"窗口函数与 GROUP BY 聚合的主要区别是？","o":["两者完全相同","窗口函数不会把多行合并为一行","窗口函数不能使用聚合函数","窗口函数会减少行数"],"a":1,"e":"每一行都保留，并附带基于窗口计算的值。"},
{"id":"sql-3-003","c":"sql","l":3,"q":"分数为 100、100、90 时，RANK() 的结果是？","o":["1, 1, 2","1, 2, 2","1, 2, 3","1, 1, 3"],"a":3,"e":"RANK 并列后会跳号。"},
{"id":"sql-3-004","c":"sql","l":3,"q":"分数为 100、100、90 时，DENSE_RANK() 的结果是？","o":["1, 1, 2","1, 2, 2","1, 1, 3","1, 2, 3"],"a":0,"e":"DENSE_RANK 并列后不跳号。"},
{"id":"sql-3-005","c":"sql","l":3,"q":"分数为 100、100、90 时，ROW_NUMBER() 的结果是？","o":["1, 2, 3（并列顺序不确定）","1, 1, 2","1, 1, 3","全部为 1"],"a":0,"e":"ROW_NUMBER 总是连续编号，并列行的先后不确定。"},
{"id":"sql-3-006","c":"sql","l":3,"q":"OVER (PARTITION BY dept ORDER BY salary DESC) 中 PARTITION BY 的作用是？","o":["对表进行物理分区","按部门划分窗口，在每个部门内单独计算","对整个结果分组聚合","按部门排序"],"a":1,"e":"类似 GROUP BY 但不合并行。"},
{"id":"sql-3-007","c":"sql","l":3,"q":"取每个部门工资前 3 名（允许并列），推荐写法是？","o":["GROUP BY dept LIMIT 3","WHERE DENSE_RANK() <= 3","在子查询中计算 DENSE_RANK() OVER (PARTITION BY dept ORDER BY salary DESC)，外层筛选 <= 3","HAVING RANK() <= 3"],"a":2,"e":"窗口函数在 WHERE 之后计算，不能直接在 WHERE 中使用。"},
{"id":"sql-3-008","c":"sql","l":3,"q":"LAG(salary, 1) OVER (ORDER BY month) 返回？","o":["第一行的 salary","后一行的 salary","按 month 排序后前一行的 salary","当前行的 salary"],"a":2,"e":"LEAD 返回后续行；没有前一行时返回 NULL 或指定的默认值。"},
{"id":"sql-3-009","c":"sql","l":3,"q":"计算累计求和（running total）的写法是？","o":["SUM(amount) OVER ()","SUM(amount) OVER (ORDER BY dt)","CUMSUM(amount)","SUM(amount) GROUP BY dt"],"a":1,"e":"带 ORDER BY 时默认窗口为 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW。"},
{"id":"sql-3-010","c":"sql","l":3,"q":"SUM(x) OVER () 的含义是？","o":["与 SUM(x) 相同只返回一行","每一行都显示全表 x 的总和","计算前一行之和","报错"],"a":1,"e":"空 OVER() 表示整个结果集构成一个窗口。"},
{"id":"sql-3-011","c":"sql","l":3,"q":"带 ORDER BY 的窗口默认帧使用 RANGE，当排序值有重复时会怎样？","o":["严格逐行累加","忽略重复行","报错","值相同的行被视为同一个对等组，累计值相同"],"a":3,"e":"需要严格逐行累计时应显式写 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW。"},
{"id":"sql-3-012","c":"sql","l":3,"q":"计算 7 日移动平均可以使用？","o":["AVG(x) GROUP BY 7","AVG(LAG(x, 7))","AVG(x) OVER (PARTITION BY 7)","AVG(x) OVER (ORDER BY dt ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)"],"a":3,"e":"ROWS 按物理行数定义窗口帧。"},
{"id":"sql-3-013","c":"sql","l":3,"q":"FIRST_VALUE(x) OVER (PARTITION BY g ORDER BY t) 返回？","o":["全表第一个 x","当前行的 x","每个分区中按 t 排序的第一个 x","分区最后一个 x"],"a":2,"e":"LAST_VALUE 在默认帧下通常返回当前行，需要扩展帧到 UNBOUNDED FOLLOWING。"},
{"id":"sql-3-014","c":"sql","l":3,"q":"NTILE(4) OVER (ORDER BY score) 的作用是？","o":["把有序行尽量平均分成 4 个桶并返回桶号","返回 4 的倍数","计算四分位数的精确值","返回前 4 行"],"a":0,"e":"常用于分层统计，各桶行数最多相差 1。"},
{"id":"sql-3-015","c":"sql","l":3,"q":"窗口函数在 SQL 逻辑执行顺序中位于？","o":["LIMIT 之后","HAVING 之后、ORDER BY 之前","FROM 之前","WHERE 之前"],"a":1,"e":"因此窗口函数可以在 SELECT 和 ORDER BY 中使用，不能在 WHERE 中使用。"},
{"id":"sql-3-016","c":"sql","l":3,"q":"MySQL 8.0 的 WINDOW 子句的作用是？","o":["设置隔离级别","创建临时窗口表","定义命名窗口供多个窗口函数复用","限制返回行数"],"a":2,"e":"如 WINDOW w AS (PARTITION BY dept ORDER BY salary)。"},
{"id":"sql-3-017","c":"sql","l":3,"q":"查找连续登录 3 天以上的用户，常用技巧是？","o":["使用 GROUP_CONCAT","使用 CROSS JOIN","日期减去 ROW_NUMBER() 得到分组键，相同键即为连续","使用 UNION"],"a":2,"e":"连续日期减去连续序号得到相同的值（gaps and islands 问题）。"},
{"id":"sql-3-018","c":"sql","l":3,"q":"递归 CTE 的写法是？","o":["WITH LOOP t","CONNECT BY","WITH RECURSIVE t AS (初始查询 UNION ALL 引用 t 的递归查询)","CREATE RECURSIVE VIEW"],"a":2,"e":"MySQL 8.0 支持；Oracle 传统写法是 CONNECT BY。"},
{"id":"sql-3-019","c":"sql","l":3,"q":"递归 CTE 的最大递归深度由哪个变量控制（MySQL）？","o":["max_sp_recursion_depth","max_join_size","cte_max_recursion_depth","max_recursion"],"a":2,"e":"默认 1000，可防止无限递归。"},
{"id":"sql-3-020","c":"sql","l":3,"q":"MySQL 8.0 的 EXPLAIN ANALYZE 与 EXPLAIN 的区别是？","o":["与 EXPLAIN 相同","只显示估计值","实际执行查询并显示每一步的实际耗时和行数","不执行查询也能显示真实耗时"],"a":2,"e":"它基于树形执行计划输出（8.0.18 起），注意会真正执行语句。"},
{"id":"sql-3-021","c":"sql","l":3,"q":"EXPLAIN 的 rows 列表示？","o":["优化器估计需要扫描的行数","表的总行数","已锁定的行数","实际返回的行数"],"a":0,"e":"估计值依赖统计信息，可能与实际差距较大。"},
{"id":"sql-3-022","c":"sql","l":3,"q":"EXPLAIN 的 filtered 列表示？","o":["按条件过滤后剩余行数的估计百分比","已过滤的行数","缓存命中率","索引的过滤率"],"a":0,"e":"rows × filtered / 100 约为传给下一步的行数。"},
{"id":"sql-3-023","c":"sql","l":3,"q":"EXPLAIN 的 type 为 eq_ref 通常出现在？","o":["全文索引","范围查询","全表扫描","连接时使用被驱动表的主键或唯一非空索引等值匹配"],"a":3,"e":"每个驱动行最多匹配被驱动表一行。"},
{"id":"sql-3-024","c":"sql","l":3,"q":"EXPLAIN 的 type 为 index 表示？","o":["使用索引精确查找","范围扫描","全索引扫描","常量查找"],"a":2,"e":"它扫描整棵索引树，通常比 ALL 好一些但仍然低效。"},
{"id":"sql-3-025","c":"sql","l":3,"q":"EXPLAIN 的 key_len 列的用途是？","o":["显示索引名长度","显示表大小","显示键值长度上限","判断联合索引实际使用了多少列"],"a":3,"e":"可空列和变长列会额外占用字节。"},
{"id":"sql-3-026","c":"sql","l":3,"q":"EXPLAIN 显示 select_type 为 DEPENDENT SUBQUERY 意味着？","o":["子查询只执行一次","子查询出错","子查询已被优化为 JOIN","相关子查询可能对外层每一行执行一次"],"a":3,"e":"可考虑改写为 JOIN 或 EXISTS（新版优化器会自动处理部分情况）。"},
{"id":"sql-3-027","c":"sql","l":3,"q":"优化器选择执行计划主要基于？","o":["SQL 的书写顺序","随机选择","基于成本的估算（统计信息）","固定规则"],"a":2,"e":"MySQL 使用基于成本的优化器（CBO）。"},
{"id":"sql-3-028","c":"sql","l":3,"q":"表数据变化很大后执行计划变差，可以执行？","o":["FLUSH LOGS","REPAIR INDEX","DROP TABLE","ANALYZE TABLE t 更新统计信息"],"a":3,"e":"InnoDB 统计信息基于采样页，可能存在误差。"},
{"id":"sql-3-029","c":"sql","l":3,"q":"强制 MySQL 使用某个索引的语法是？","o":["WITH INDEX idx","FROM t FORCE INDEX (idx)","INDEX HINT idx","USE ONLY idx"],"a":1,"e":"也有 USE INDEX 和 IGNORE INDEX；8.0 还支持优化器提示 /*+ INDEX(...) */。"},
{"id":"sql-3-030","c":"sql","l":3,"q":"MySQL 8.0 的直方图（histogram）用于？","o":["为无索引列提供数据分布统计，改进选择率估算","压缩数据","替代索引","加速插入"],"a":0,"e":"ANALYZE TABLE t UPDATE HISTOGRAM ON col 创建直方图。"},
{"id":"sql-3-031","c":"sql","l":3,"q":"MySQL 8.0.18 起，没有可用索引的等值连接默认使用？","o":["嵌套循环全表扫描","笛卡尔积","哈希连接（Hash Join）","排序合并连接"],"a":2,"e":"8.0.20 起哈希连接完全取代了块嵌套循环（BNL）。"},
{"id":"sql-3-032","c":"sql","l":3,"q":"MRR（Multi-Range Read）优化的作用是？","o":["并行执行多条 SQL","合并多个索引","把二级索引得到的主键排序后再回表，将随机 IO 转为顺序 IO","读取多个副本"],"a":2,"e":"EXPLAIN 的 Extra 会显示 Using MRR。"},
{"id":"sql-3-033","c":"sql","l":3,"q":"MySQL 8.0 的索引跳跃扫描（Skip Scan）允许？","o":["跳过事务","在联合索引 (a, b) 上只有 b 条件时，按 a 的不同值分段扫描","跳过回表","跳过全表扫描的所有限制"],"a":1,"e":"适用于前导列区分度很低的情况。"},
{"id":"sql-3-034","c":"sql","l":3,"q":"“延迟关联”优化深分页的思路是？","o":["关闭索引","增加 LIMIT","先通过覆盖索引查出主键，再与原表 JOIN 取完整行","使用 HAVING"],"a":2,"e":"减少了大量偏移行的回表开销。"},
{"id":"sql-3-035","c":"sql","l":3,"q":"MySQL 8.0 新增的降序索引的意义是？","o":["只能降序查询","提升写入速度","降低索引大小","ORDER BY a ASC, b DESC 等混合方向排序也可直接利用索引"],"a":3,"e":"8.0 之前 DESC 关键字会被解析但被忽略。"},
{"id":"sql-3-036","c":"sql","l":3,"q":"MySQL 8.0 的不可见索引（invisible index）的用途是？","o":["在不删除索引的情况下验证删除它对性能的影响","隐藏敏感数据","加快写入","替代主键"],"a":0,"e":"ALTER TABLE t ALTER INDEX idx INVISIBLE。"},
{"id":"sql-3-037","c":"sql","l":3,"q":"MySQL 8.0.13 起支持的函数索引示例是？","o":["CREATE FUNCTION INDEX","不支持函数索引","CREATE INDEX idx ON t ((LOWER(email)))","CREATE INDEX idx ON t (FUNC email)"],"a":2,"e":"函数表达式需要额外用括号包起来。"},
{"id":"sql-3-038","c":"sql","l":3,"q":"InnoDB 聚簇索引的叶子节点存储的是？","o":["完整的行数据","主键值和行指针","只有主键","二级索引"],"a":0,"e":"因此一张 InnoDB 表只能有一个聚簇索引。"},
{"id":"sql-3-039","c":"sql","l":3,"q":"InnoDB 表没有定义主键时会怎样？","o":["使用第一个非空唯一索引作为聚簇索引，否则生成隐藏的 6 字节 row_id","不使用聚簇索引","报错无法建表","使用第一列"],"a":0,"e":"推荐总是显式定义主键。"},
{"id":"sql-3-040","c":"sql","l":3,"q":"InnoDB 数据页的默认大小是？","o":["4KB","16KB","64KB","8KB"],"a":1,"e":"由 innodb_page_size 决定，初始化实例后不能修改。"},
{"id":"sql-3-041","c":"sql","l":3,"q":"B+ 树相比 B 树更适合数据库索引的原因不包括？","o":["叶子节点通过链表相连，便于范围扫描","查询路径长度稳定","B+ 树的非叶子节点存储完整数据","非叶子节点只存键，扇出更大、树更矮"],"a":2,"e":"B 树的非叶子节点存储数据，B+ 树只在叶子节点存储数据。"},
{"id":"sql-3-042","c":"sql","l":3,"q":"InnoDB 的 Buffer Pool 的作用是？","o":["存储连接信息","存储 binlog","在内存中缓存数据页和索引页","缓存 SQL 查询结果"],"a":2,"e":"生产环境通常设置为物理内存的 50%~75%。"},
{"id":"sql-3-043","c":"sql","l":3,"q":"InnoDB Buffer Pool 的 LRU 链表被分为 young 和 old 两部分，目的是？","o":["减少锁","加快写入","防止全表扫描等一次性访问把热点数据挤出缓存","支持事务"],"a":2,"e":"新读入的页先放入 old 区，停留一段时间后再次访问才进入 young 区。"},
{"id":"sql-3-044","c":"sql","l":3,"q":"InnoDB 的 Change Buffer 优化的是？","o":["SELECT 查询","主键插入","非唯一二级索引的写入，延迟合并以减少随机 IO","唯一索引的唯一性检查"],"a":2,"e":"唯一索引需要读取页面检查唯一性，因此不能使用 change buffer。"},
{"id":"sql-3-045","c":"sql","l":3,"q":"InnoDB 的自适应哈希索引（AHI）是？","o":["用户手动创建的哈希索引","InnoDB 根据访问模式自动在内存中为热点页建立的哈希索引","全文索引","MEMORY 引擎的索引"],"a":1,"e":"它无法被用户显式创建，可以通过参数关闭。"},
{"id":"sql-3-046","c":"sql","l":3,"q":"InnoDB 的 doublewrite buffer 用于解决？","o":["部分页写入（页撕裂）导致的数据页损坏","查询缓存失效","主从延迟","死锁"],"a":0,"e":"写数据页前先把页写到 doublewrite 区，崩溃后可以用于修复。"},
{"id":"sql-3-047","c":"sql","l":3,"q":"innodb_flush_log_at_trx_commit = 1 的含义是？","o":["每秒刷盘一次","由操作系统决定刷盘","从不刷盘","每次事务提交时把 redo log 写入并刷到磁盘"],"a":3,"e":"设为 1 最安全；0 和 2 在崩溃时可能丢失约 1 秒的事务。"},
{"id":"sql-3-048","c":"sql","l":3,"q":"sync_binlog = 1 的含义是？","o":["不同步","每 1000 个事务同步一次","每秒同步一次","每次事务提交时把 binlog 同步到磁盘"],"a":3,"e":"与 innodb_flush_log_at_trx_commit = 1 合称“双 1”配置。"},
{"id":"sql-3-049","c":"sql","l":3,"q":"MySQL 通过什么机制保证 redo log 与 binlog 的一致性？","o":["异步复制","只写 binlog","两阶段提交：redo prepare → 写 binlog → redo commit","只写 redo log"],"a":2,"e":"崩溃恢复时根据 binlog 是否完整决定提交或回滚 prepare 状态的事务。"},
{"id":"sql-3-050","c":"sql","l":3,"q":"WAL（Write-Ahead Logging）的含义是？","o":["不写日志","先写数据页再写日志","只在内存中修改","修改数据页前先写日志，日志落盘即可认为事务持久"],"a":3,"e":"顺序写日志比随机写数据页快得多。"},
{"id":"sql-3-051","c":"sql","l":3,"q":"redo log 的 checkpoint 的作用是？","o":["把脏页刷盘后推进检查点，使对应的 redo 空间可以被重用","清理 undo log","创建备份","提交事务"],"a":0,"e":"redo log 是循环写入的，需要 checkpoint 释放空间。"},
{"id":"sql-3-052","c":"sql","l":3,"q":"InnoDB 的 purge 线程负责？","o":["刷新脏页","处理死锁","清理不再被任何快照需要的 undo log 和已删除标记的记录","复制数据"],"a":2,"e":"长事务会阻止 purge，导致 undo 膨胀。"},
{"id":"sql-3-053","c":"sql","l":3,"q":"MVCC 的全称和作用是？","o":["多版本并发控制，让读写互不阻塞","多列复合约束","主从版本控制","多值约束检查"],"a":0,"e":"InnoDB 通过 undo 版本链和 ReadView 实现 MVCC。"},
{"id":"sql-3-054","c":"sql","l":3,"q":"InnoDB 行记录中用于实现 MVCC 的隐藏列包括？","o":["CREATE_TIME 和 DELETE_TIME","DB_TRX_ID 和 DB_ROLL_PTR","ROW_HASH","DB_VERSION 和 DB_TIME"],"a":1,"e":"DB_TRX_ID 是最后修改的事务 ID，DB_ROLL_PTR 指向 undo 中的旧版本。"},
{"id":"sql-3-055","c":"sql","l":3,"q":"ReadView 中判断某版本是否可见的依据是？","o":["行的主键大小","随机","版本的事务 ID 与 ReadView 中的活跃事务列表、最小和最大事务 ID 比较","版本的时间戳"],"a":2,"e":"不可见时沿 roll_pointer 回溯到更旧的版本。"},
{"id":"sql-3-056","c":"sql","l":3,"q":"RC 与 RR 隔离级别在 ReadView 生成时机上的区别是？","o":["RR 每次 SELECT 生成","RC 在事务开始时生成一次","RC 每次 SELECT 生成新 ReadView，RR 在事务第一次快照读时生成并复用","两者相同"],"a":2,"e":"这就是 RC 会出现不可重复读而 RR 不会的原因。"},
{"id":"sql-3-057","c":"sql","l":3,"q":"START TRANSACTION WITH CONSISTENT SNAPSHOT 的作用是？","o":["开启只读事务","设置 SERIALIZABLE","立即创建一致性读视图","锁定所有表"],"a":2,"e":"普通 BEGIN 要到第一条快照读语句才创建 ReadView。"},
{"id":"sql-3-058","c":"sql","l":3,"q":"InnoDB RR 级别下，快照读与当前读混用可能出现的问题是？","o":["数据丢失","同一事务中普通 SELECT 看不到某行，但 UPDATE 能更新到它（幻读的变体）","死锁必然发生","不会有任何问题"],"a":1,"e":"UPDATE 是当前读，读取最新已提交版本，之后的快照读也能看到自己的修改。"},
{"id":"sql-3-059","c":"sql","l":3,"q":"InnoDB 的间隙锁（Gap Lock）锁定的是？","o":["整张表","整个数据页","单条记录","索引记录之间的间隙，阻止在其中插入"],"a":3,"e":"间隙锁之间互相兼容，它只阻止插入。"},
{"id":"sql-3-060","c":"sql","l":3,"q":"Next-Key Lock 是？","o":["两个记录锁","表锁和行锁","插入意向锁","记录锁加上该记录之前的间隙锁（左开右闭区间）"],"a":3,"e":"RR 级别下 InnoDB 默认使用 next-key lock 进行当前读加锁。"},
{"id":"sql-3-061","c":"sql","l":3,"q":"在 READ COMMITTED 级别下，InnoDB 的间隙锁？","o":["与 RR 相同","使用更多","变为表锁","基本不使用（外键和唯一性检查除外）"],"a":3,"e":"因此 RC 下并发更好，但可能出现幻读。"},
{"id":"sql-3-062","c":"sql","l":3,"q":"唯一索引上的等值查询命中一条存在的记录时，InnoDB（RR）加的锁会退化为？","o":["记录锁","表锁","间隙锁","next-key lock"],"a":0,"e":"唯一性保证不会有重复值插入，因此不需要锁间隙。"},
{"id":"sql-3-063","c":"sql","l":3,"q":"等值查询的值不存在时，InnoDB（RR）通常会加？","o":["间隙锁","表锁","记录锁","不加锁"],"a":0,"e":"锁住该值所在的间隙，防止其他事务插入该值。"},
{"id":"sql-3-064","c":"sql","l":3,"q":"插入意向锁（Insert Intention Lock）的特点是？","o":["只用于删除","是一种间隙锁，多个事务在同一间隙插入不同位置时互不阻塞","会阻塞所有读","是表级锁"],"a":1,"e":"但它会被其他事务持有的间隙锁阻塞。"},
{"id":"sql-3-065","c":"sql","l":3,"q":"意向锁（IS/IX）的作用是？","o":["表级标记，让加表锁时快速判断表中是否有行锁","锁定行","防止死锁","替代行锁"],"a":0,"e":"意向锁之间互相兼容，主要与表级 S/X 锁冲突。"},
{"id":"sql-3-066","c":"sql","l":3,"q":"MDL（元数据锁）可能导致的问题是？","o":["行锁变成表锁","数据丢失","索引失效","长事务持有 MDL 读锁时执行 ALTER TABLE，后续所有查询被阻塞"],"a":3,"e":"DDL 前应检查 information_schema.innodb_trx 中的长事务。"},
{"id":"sql-3-067","c":"sql","l":3,"q":"查看最近一次死锁信息的命令是？","o":["SHOW LOCKS","EXPLAIN DEADLOCK","SHOW DEADLOCKS","SHOW ENGINE INNODB STATUS"],"a":3,"e":"LATEST DETECTED DEADLOCK 部分记录了死锁双方的事务和锁信息。"},
{"id":"sql-3-068","c":"sql","l":3,"q":"MySQL 8.0 中查看当前锁信息的系统表是？","o":["information_schema.innodb_locks","sys.lock_table","mysql.locks","performance_schema.data_locks"],"a":3,"e":"5.7 的 information_schema.innodb_locks 在 8.0 中已被移除。"},
{"id":"sql-3-069","c":"sql","l":3,"q":"SELECT ... FOR UPDATE NOWAIT（MySQL 8.0）的作用是？","o":["等待锁直到超时","要加锁的行被锁定时立即报错而不等待","不加锁读取","跳过被锁的行"],"a":1,"e":"SKIP LOCKED 则跳过被锁的行，常用于任务队列。"},
{"id":"sql-3-070","c":"sql","l":3,"q":"SELECT ... FOR UPDATE SKIP LOCKED 适合的场景是？","o":["数据备份","生成报表","统计总数","多个消费者并发从任务表领取任务"],"a":3,"e":"结果集不一致，不适合需要完整一致数据的查询。"},
{"id":"sql-3-071","c":"sql","l":3,"q":"两个事务以相反顺序更新相同的两行，最可能导致？","o":["幻读","锁升级","脏读","死锁"],"a":3,"e":"InnoDB 会检测到死锁并回滚其中一个事务。"},
{"id":"sql-3-072","c":"sql","l":3,"q":"InnoDB 在高并发下关闭死锁检测（innodb_deadlock_detect = OFF）的代价是？","o":["数据损坏","死锁只能依靠 innodb_lock_wait_timeout 超时解除","查询变慢","无法加锁"],"a":1,"e":"大量线程竞争同一行时，死锁检测本身可能消耗大量 CPU。"},
{"id":"sql-3-073","c":"sql","l":3,"q":"丢失更新问题（两个事务读取后各自写回）的解决方法不包括？","o":["使用 UPDATE t SET x = x + 1 原子更新","改用 READ UNCOMMITTED","SELECT ... FOR UPDATE","乐观锁版本号"],"a":1,"e":"在应用层读取后再写回容易覆盖其他事务的修改。"},
{"id":"sql-3-074","c":"sql","l":3,"q":"RR 级别下，可以完全避免“先读后写”造成的写偏斜（write skew）吗？","o":["只有 RC 能避免","写偏斜不存在","能完全避免","不能完全避免，需要当前读加锁或 SERIALIZABLE"],"a":3,"e":"快照读基于旧数据做判断，并发事务可能同时违反约束。"},
{"id":"sql-3-075","c":"sql","l":3,"q":"InnoDB 的 SERIALIZABLE 级别下，普通 SELECT（autocommit 关闭时）会？","o":["加排他锁","隐式转为 SELECT ... FOR SHARE","报错","不加锁"],"a":1,"e":"因此读写之间会相互阻塞。"},
{"id":"sql-3-076","c":"sql","l":3,"q":"长事务的危害不包括？","o":["undo log 无法清理而膨胀","主从延迟和回滚耗时","提高查询缓存命中率","长时间持有锁"],"a":2,"e":"应设置监控并尽量拆分大事务。"},
{"id":"sql-3-077","c":"sql","l":3,"q":"MySQL 默认的异步复制存在的风险是？","o":["从库无法读取","主库无法写入","主库崩溃时，已提交但未传到从库的事务可能丢失","数据一定不一致"],"a":2,"e":"半同步复制要求至少一个从库确认收到后才返回提交成功。"},
{"id":"sql-3-078","c":"sql","l":3,"q":"主从复制中，从库负责执行 relay log 的线程是？","o":["SQL 线程（8.0 中称为 applier 线程）","purge 线程","IO 线程","binlog dump 线程"],"a":0,"e":"IO（receiver）线程负责拉取主库 binlog 并写入 relay log。"},
{"id":"sql-3-079","c":"sql","l":3,"q":"binlog 格式中，最能保证主从数据一致的是？","o":["STATEMENT","TEXT","MIXED","ROW"],"a":3,"e":"STATEMENT 格式下 NOW()、UUID() 等不确定函数可能导致不一致；8.0 默认为 ROW。"},
{"id":"sql-3-080","c":"sql","l":3,"q":"读写分离架构中“刚写入就读不到”的原因是？","o":["索引失效","主键冲突","主从复制延迟","事务隔离级别过高"],"a":2,"e":"可让关键读走主库或在写后短时间内路由到主库。"},
{"id":"sql-3-081","c":"sql","l":3,"q":"GTID 在 MySQL 复制中的作用是？","o":["压缩 binlog","为每个事务分配全局唯一 ID，简化故障切换和定位复制位置","加密复制数据","替代主键"],"a":1,"e":"无需再手动指定 binlog 文件名和位置。"},
{"id":"sql-3-082","c":"sql","l":3,"q":"MySQL 分区表中，分区裁剪（partition pruning）是指？","o":["查询条件包含分区键时只扫描相关分区","合并分区","压缩分区","删除旧分区"],"a":0,"e":"EXPLAIN 的 partitions 列显示访问了哪些分区。"},
{"id":"sql-3-083","c":"sql","l":3,"q":"MySQL 分区表的主键或唯一索引必须？","o":["没有限制","只能是自增列","包含所有分区键列","不包含分区键"],"a":2,"e":"这是 MySQL 分区的硬性约束。"},
{"id":"sql-3-084","c":"sql","l":3,"q":"在线 DDL（MySQL 8.0）中 ALGORITHM=INSTANT 的意义是？","o":["只修改数据字典元数据，几乎瞬间完成，例如添加列","只能删除索引","锁表复制","重建整张表"],"a":0,"e":"8.0.29 起 INSTANT 支持在任意位置添加列和删除列。"},
{"id":"sql-3-085","c":"sql","l":3,"q":"大表加索引时 ALGORITHM=INPLACE, LOCK=NONE 的含义是？","o":["在从库执行","只读模式","在不复制整表的情况下构建索引，期间允许并发 DML","锁表并复制"],"a":2,"e":"开始和结束阶段仍需短暂获取 MDL 排他锁。"},
{"id":"sql-3-086","c":"sql","l":3,"q":"SQL 中 IN 与 EXISTS 的选择，在 MySQL 8.0 中？","o":["IN 总是更快","IN 不能使用索引","EXISTS 总是更快","优化器通常会将二者转换为半连接，差异不大"],"a":3,"e":"半连接策略包括 FirstMatch、LooseScan、Materialization 等。"},
{"id":"sql-3-087","c":"sql","l":3,"q":"MySQL 8.0.16 起支持并真正执行的约束是？","o":["CHECK 约束","DEFERRABLE 外键","EXCLUDE 约束","ASSERTION"],"a":0,"e":"8.0.16 之前 CHECK 会被解析但被忽略。"},
{"id":"sql-3-088","c":"sql","l":3,"q":"count(*) 查询大表很慢时，以下哪种思路可以接受？","o":["使用 SELECT * 再在程序中计数","使用 FULL JOIN","使用 COUNT(col) 一定更快","使用单独的计数表或缓存，并在事务中维护"],"a":3,"e":"也可以用 EXPLAIN 或 information_schema 获取近似值（不精确）。"},
{"id":"sql-3-089","c":"sql","l":3,"q":"OR 条件改写为 UNION ALL 时要注意？","o":["避免同一行同时满足两个条件而被重复返回","必须使用相同的索引","不能使用 WHERE","UNION ALL 会自动去重"],"a":0,"e":"可在第二个分支中添加排除第一个条件的谓词。"},
{"id":"sql-3-090","c":"sql","l":3,"q":"JOIN 的 ON 条件与 WHERE 条件对 INNER JOIN 结果的影响是？","o":["ON 中的条件会被忽略","结果总是不同","结果相同","WHERE 中的条件会被忽略"],"a":2,"e":"只有外连接时两者的位置才会影响结果。"},
{"id":"sql-3-091","c":"sql","l":3,"q":"SELECT ... WHERE a = 1 ORDER BY b LIMIT 10，最优的索引通常是？","o":["(b, a)","(a) 单列","(a, b)","(b)"],"a":2,"e":"(a, b) 能定位 a = 1 并直接按 b 的顺序读取前 10 行，避免排序。"},
{"id":"sql-3-092","c":"sql","l":3,"q":"联合索引列的顺序设计原则通常是？","o":["范围条件列放最前","按字母顺序排列","区分度最低的列放最前","等值条件列在前，范围条件列在后，并兼顾区分度和排序需求"],"a":3,"e":"范围列之后的列无法继续用于索引定位。"},
{"id":"sql-3-093","c":"sql","l":3,"q":"SQL 中 NOT IN 子查询改写为 LEFT JOIN ... WHERE b.id IS NULL 的主要原因是？","o":["没有原因","LEFT JOIN 语法更短","NOT IN 不能执行","NULL 语义更安全且通常可以被高效执行为反连接"],"a":3,"e":"子查询结果中出现 NULL 时，NOT IN 会返回空结果。"},
{"id":"sql-3-094","c":"sql","l":3,"q":"在高并发场景下，使用 UUID 作为 InnoDB 主键的主要问题是？","o":["无法排序","主键随机且长，导致页分裂、索引膨胀和缓存命中率低","不能被索引","无法保证唯一"],"a":1,"e":"可以用有序 UUID（如 UUID_TO_BIN(uuid, 1)）或雪花 ID 缓解。"},
{"id":"sql-3-095","c":"sql","l":3,"q":"Online 业务中批量删除千万行数据的推荐方式是？","o":["锁表后删除","一条 DELETE 删除全部","按主键范围分批删除，每批提交","关闭 binlog 删除"],"a":2,"e":"大事务会导致锁持有时间长、主从延迟和 undo 膨胀。"},
{"id":"sql-3-096","c":"sql","l":3,"q":"SQL 注入的根本防御方法是？","o":["过滤所有单引号","使用参数化查询（预编译语句）","在前端校验输入","使用存储过程即可"],"a":1,"e":"参数作为数据传递，不会被当作 SQL 代码解析。"},
{"id":"sql-3-097","c":"sql","l":3,"q":"PERCENT_RANK() 的计算公式是？","o":["(rank - 1) / (分区总行数 - 1)","row_number / 总行数","(rank + 1) / 总行数","rank / 总行数"],"a":0,"e":"CUME_DIST 则为小于等于当前值的行数 / 总行数。"},
{"id":"sql-3-098","c":"sql","l":3,"q":"InnoDB 的 Online DDL 期间并发 DML 的修改会先记录在？","o":["查询缓存中","undo log 中","在线变更日志（row log），DDL 结束时重放","binlog 中"],"a":2,"e":"日志大小受 innodb_online_alter_log_max_size 限制，超出会导致 DDL 失败。"},
{"id":"sql-3-099","c":"sql","l":3,"q":"EXPLAIN FORMAT=TREE（MySQL 8.0）的输出特点是？","o":["以树形结构展示迭代器执行计划及估计成本","显示实际耗时","输出 JSON","只显示表名"],"a":0,"e":"EXPLAIN ANALYZE 在此基础上增加了实际执行的统计信息。"},
{"id":"sql-3-100","c":"sql","l":3,"q":"LIMIT 与 ORDER BY 一起使用但排序列不唯一时，分页可能出现？","o":["报错","性能提升","不同页之间出现重复或遗漏的行","总是稳定"],"a":2,"e":"应在 ORDER BY 中加入唯一列（如主键）保证排序确定。"}
];
